### ISSUE TITLE
A new release with repaired signatures is needed for SimRel by the end of the day Wednesday

### ISSUE THREAD

**Issue by merks** [eclipse/lsp4e#1019]
Content signed after the certificate expired last Tuesday is broken:

https://github.com/eclipse-simrel/simrel.build/issues/363

Specifically these two jars have broken signatures

![image](https://github.com/eclipse/lsp4e/assets/208716/332bfdd3-298c-4a5a-8831-6d7fe67bd00f)

The other content was signed before the certificate expired:

https://download.eclipse.org/oomph/archive/reports-extra/lsp4e-releases-0.26.1/download.eclipse.org/lsp4e/releases/0.26.1/index.html

I would highly recommend incrementing the version of the bundle with the broken signature.

cc  @jonahgraham  @akurtakov

**Comment by merks** [comment]
Yes, it looks good:

https://download.eclipse.org/oomph/archive/reports-extra/lsp4e-snapshots/download.eclipse.org/lsp4e/snapshots/index.html

![image](https://github.com/eclipse/lsp4e/assets/208716/be75d5f0-e4bb-4171-8e0a-06d31f40f109)

Thank you.  ❤️

**Comment by merks** [comment]
I guess technically it's not complete until you contribute a release, but I assume that's in the works.  👍

**Comment by mickaelistria** [comment]
Not really, we hadn't plan a new release before SimRel as we already produced one recently.
So I'm releasing a new one right now.

**Comment by merks** [comment]
Yes, it's badly needed and also by WildWebDeveloper's build which has a copy of this bundle in its update site.
