### ISSUE TITLE
Add "hide fields" filter to outline view's toolbar

### ISSUE THREAD

**Issue by travkin79** [eclipse/lsp4e#1073]
I'd like to add a toolbar action to the outline view for hiding fields. This filter is very common and is available, e.g. for Java (JDT) and C++ (CDT). It would look like very much like in JDT (selected button in the following screenshot):

![image](https://github.com/user-attachments/assets/e95aadae-866a-4832-8777-ee4d7f168c30)

Are there any objections on implementing that filter in LSP4E (for all language servers)?

This is a follow-up issue to #254.

**Comment by rubenporras** [comment]
That would be appreciated from my side. Which elements are you planning to offer hiding with an icon?

**Comment by travkin79** [comment]
For now, I would only add one button "hide fields".
