### ISSUE TITLE
LSP4E doesn't support progress

### ISSUE THREAD

**Issue by michelkaporin** [eclipse/lsp4e#109]
LSP4E doesn't support progress notifications from the server. Snyk is happy to contribute implementation on that and collaborate on the design. We were thinking of having the following approach:

- create a map progressToken:ProgressMonitor
- show progress in the UI (start an empty job with the progress monitor)
- update the progress monitor whenever a progress is reported
- exit the job when the server signals completion (progress end)
 
Please let us know if the approach makes sense and PR on that is welcome.

cc @bastiandoetsch @martinlippert

**Comment by martinlippert** [comment]
@mickaelistria Would love to hear your thoughts on this.

**Comment by bastiandoetsch** [comment]
Great! Hopefully, a first version is not gonna be long - we already got something internally, that I just need to move to lsp4e classes (mainly `LanguageClientImpl`). Also, please don't hesitate to point our possible improvements - we are probably way less seasoned Eclipse engineers than you :).

**Comment by rubenporras** [comment]
@martinlippert , thanks a lot, I have not seen this issue. 
@bastiandoetsch would you mind posting your work? Do not worry about its state ;) I also posted mine in #120 which is only WIP. You can also contribute to my commit, if you prefer. I think our approaches are similar.

**Comment by rubenporras** [comment]
Issue solved by https://github.com/eclipse/lsp4e/pull/120
