### ISSUE TITLE
CI build fails

### ISSUE THREAD

**Issue by ghentschke** [eclipse/lsp4e#1109]
I've seen that the CI build failed with: 
`Error: 1,284 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-clean-plugin:3.4.0:clean (default-clean) on project org.eclipse.lsp4e: Failed to clean project: Failed to delete D:\a\lsp4e\lsp4e\org.eclipse.lsp4e\target\org.eclipse.lsp4e-0.18.14-SNAPSHOT.jar -> [Help 1]`

Does anybody has an idea?

**Comment by sebthom** [comment]
I am currently seeing a lot of funky errors on Windows. My guess it is somehow related to https://github.com/eclipse/lsp4e/issues/1103

**Comment by sebthom** [comment]
The issue apparently not only affects the GHA Windows builds but most of the Jenkins builds now. You can monitor https://github.com/eclipse/lsp4e/issues/1103 for progress.
