### ISSUE TITLE
0.4.5 tag in repo

### ISSUE THREAD

**Issue by jonahgraham** [eclipse/lsp4e#124]
There is a [0.4.5 tag](https://github.com/eclipse/lsp4e/releases/tag/0.4.5) that was just recently added to LSP4E. It looks like an accident as 0.4.5 as a version would be a long time ago.

The tag has the same comment as commit 9ef09a231532ffbe0529dbcfe30e2597eb946866

Can I delete it?

cc: @ahmedneilhussain

**Comment by mickaelistria** [comment]
Yes, feel free to delete this tag. It comes from a wrong push on my end.

**Comment by jonahgraham** [comment]
Done.
