### ISSUE TITLE
No way to extend symbol kind images

### ISSUE THREAD

**Issue by jjohnstn** [eclipse/lsp4e#131]
The Dockerfile editor in Linux Tools uses lsp4e.  The dockerfile has a set of commands inside of it.  Currently, the dockerfile designates the commands as functions which results in the Function image used for each command which isn't a perfect match.  It would be nice to have an extension to either add a new symbol kind with image or as a fall-back, to specify an image for the symbolkind.

**Comment by mickaelistria** [comment]
I'm not really enthusiastic about adding too much extensibility/customization to LSP4E. LSP4E is about supporting a protocol, and supporting a protocol is not something that requires customization usually.
For example, here are the existing symbol kinds: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#symbolKind ; the dockerfile should probably pick another kind, or none; and then LSP4E -and others- would give better results.

**Comment by jjohnstn** [comment]
What about adding a Command symbol?  I would think there would be other examples of files that contain commands (e.g. execution scripts).
