### ISSUE TITLE
Feature Request: Specify initializationOptions

### ISSUE THREAD

**Issue by bastiandoetsch** [eclipse/lsp4e#159]
Hi,

I haven't found a way to specify initializationOptions for the initialize message or overwrite capabilities. It would be quite helpful to have this feature to provide a language server with the correct capabilities & options based on the client that is talking to it.

Cheers
Bastian

**Comment by bastiandoetsch** [comment]
Hm. It looks like [this](https://github.com/eclipse/lsp4e/pull/158) potentially solves it.

**Comment by sebthom** [comment]
The overridable getInitializeOptions method already exists. What exactly are you missing?

**Comment by bastiandoetsch** [comment]
Didn't see it before - will close this. Sorry...
