### ISSUE TITLE
Get serverInfo SPI

### ISSUE THREAD

**Issue by CalamarBicefalo** [eclipse/lsp4e#187]
I might be missing this feature, but cannot find an easy way to obtain the initialize result attribute `serverInfo`. 

The [spec defines this as an optional attribute](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initialize):

```
interface [InitializeResult](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initializeResult) {
	/**
	 * The capabilities the language server provides.
	 */
	capabilities: [ServerCapabilities](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#serverCapabilities);

	/**
	 * Information about the server.
	 *
	 * @since 3.15.0
	 */
	serverInfo?: {
		/**
		 * The name of the server as defined by the server.
		 */
		name: string;

		/**
		 * The server's version as defined by the server.
		 */
		version?: string;
	};
}
```

Would it be possible to add a method to fetch the serverInfo on initialize?

**Comment by mickaelistria** [comment]
We try to minimize the amount of API/SPI in LSP4E, to ease maintenance and also because the purpose of LSP is to avoid too much customization.
So can you please elaborate more about your needs? Maybe this can be directly covered in LSP4E default behavior and then serve all integrations?

**Comment by CalamarBicefalo** [comment]
Makes sense. 

Even if it is not SPI, it would be nice to be able to somehow get that info - as it is part of the protocol. Our use case to see if that helps, is that we use the server version to define our LSP version, as we have extended it a little bit to suit our needs.

Based on the server version, the client has the ability to update the server. It cannot really be done with capabilities, because sometimes we just break contracts with our extended messages.

**Comment by mickaelistria** [comment]
To be honest, I don't think integrating with language servers that requires lots of internal message and intentionally diverge too far from the protocol to be actually compliant with standard protocol is in the scope of LSP4E, and I don't think adding support for it is likely to make LSP4E more successful on the long run.
Your use-case may be achievable in a more standard way by making the language server sending a custom notification to the client, and adding in each client a custom listener for this notification to react by eg. downloading the new version of the language server. An even better solution, if you don't think offering choice to your user is that important, is to have the LS itself downloading a new version when available and switching to this new version.

**Comment by bastiandoetsch** [comment]
We try not to extend the protocol if not needed, but some features (e.g. Authentication) is not supported by it. So for these cases, we need custom messages, and we have of course custom handlers, defined with LSP4j annotations. We're on the same page with that.

Nonetheless, we would need the server version information to handle breaking changes - in this case, we prefixed an existing notification with a namespace component, so it would never collide with other messages. To cater for such breaking changes, our client should have a way to see the version of the server it is talking to - and LSP, as defined by MS, actually provides it as `InitializationResult`. Why not expose the information received with a simple property in e.g. `LanguageServerWrapper`?

**Comment by CalamarBicefalo** [comment]
Thank you very much for the input @mickaelistria. Whilst I see where you are coming from, and I do understand how optimising lsp4e for edge cases does not make sense, if you think about it, this is not what we are asking here.

The thing is, our use case really is all about getting the version of the server [which is defined in the LSP standard](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initialize). In a way, how we might use that version really is up to us and is out of the scope of lsp4e. 

Now you were suggesting using a "more standard" mechanism like notifications. However, that solution is achieving the opposite effect here, as we are effectively deviating from the standard to get something that is standardised - server version.

If we really think this is not a reasonable ask, that's cool. Otherwise, we'd be happy to contribute if it is not available.

In the meanwhile, as a workaround. Can we intercept arbitrary messages with lsp4e so we could implement our needs?

**Comment by rubenporras** [comment]
I have looked at it, and I think having an API to get the serverInfo should be quite simple.

It should just be an extra line in the `LanguageServerWrapper`

```
			}).thenAccept(res -> {
				serverCapabilities = res.getCapabilities();
				this.initiallySupportsWorkspaceFolders = supportsWorkspaceFolders(serverCapabilities);
			}).thenRun(() -> {

```
to save res.getServerInfo() into a field and then a method to retrieve it. It could also be a general improvement that when logging errors, one could attach the server information to the logs, as requested by https://github.com/eclipse/lsp4e/issues/172#issuecomment-1173649874

We do not need to do it for this issue, but it shows that the information could be used in a generic way for improving LSP4E.

So from my point of view, if someone volunteers to do it, I think it would be a nice addition with not much added complexity.

**Comment by rubenporras** [comment]
Regarding the thing of updating the server from the client, we have build this functionality as well in our client, but we do not ask the server about its version, because that means that to retrieve the information the server must be started first. We have built a repository from where to download servers, and the version an name of the server is just part of name of the file uploaded to the repository.

**Comment by CalamarBicefalo** [comment]
After considering our options, we agree with @rubenporras suggestion, and will go down that path. So we'll be leaving the server version aside.

Thank you all very much for your input.
