### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by CalamarBicefalo** [eclipse/lsp4e#188]
Hello folks, I was wondering what's the best way to implement some neat integration tests for our client.

I was hoping to get some test scaffolding at a high level (LSP I/O) where I could do something like this:

```
spyableServer = startMyLSP4EBasedPlugin()

initRequest = spyableServer.requests[0]

// assert it is an init request with the right options...
```

So to reiterate, thinking of having integration tests where the I/O is all about LSP for very high level sanity checks. I have been browsing your test suite trying to get inspiration but couldn't find anything similar, so I was hoping you could send a pointer in the right direction?

Also feel free to close this right away if it violates your issue reporting policies.

**Comment by mickaelistria** [comment]
As it's not an issue nor an enhancement request about current state of LSP4E, an issue is not the best media. GitHub Discussions are enabled for that.

**Comment by CalamarBicefalo** [comment]
Thanks @mickaelistria , I'll move it there.

I guess the one thing that could be considered an enhancement request is testing utils for integration tests. Very much like Spring offers a MockServer or Web Testing clients. This is something that makes sense for lsp4e to offer (at least from my perspective).

But I'll move it to discussions as suggested.
