### ISSUE TITLE
language servers background jobs keep hanging around.

### ISSUE THREAD

**Issue by jcompagner** [eclipse/lsp4e#213]
reported first here: https://github.com/eclipse/wildwebdeveloper/issues/851

but i do see that job is created here:

https://github.com/eclipse/lsp4e/blob/2632a5543974da44ec5ee942823ddf40c67bf104/org.eclipse.lsp4e/src/org/eclipse/lsp4e/progress/LSPProgressManager.java#L99

and that 99 line i think is never hit? there is never and "end" event?

**Comment by rubenporras** [comment]
I would guess so, there where no end event. How would you propose to address the issue?

**Comment by jcompagner** [comment]
not sure, are tehre any events coming in? it could be even for me it is always in the queue.pollFirst and that returns null and then it goes again ...

for example i am a litle bit more busy this afternoon and i have already this:

![image](https://user-images.githubusercontent.com/3274268/185953607-e2ece1eb-41a4-4fae-ada5-a72c993e03e2.png)


also see the job in the lower right corner, constantly saying i am running.. that is also distracting..

but isn't there something else we can ask are you still valid are you still alive? like the LangaugeServer itself?

**Comment by jcompagner** [comment]
this is now a really annoying behavior, my progress view is getting bigger and bigger and i always have a running job in the lower right corner, so i really hope this will be fixed soon, @mickaelistria can this be something in WWD? Should there be an end event that is somehow not coming for the angular language server i guess?

**Comment by rubenporras** [comment]
@jcompagner , I think that WWD should send an event signaling that the job has finished, if not, how would the client know that the job is no longer running on the server? As far as I read the spec, there is no endpoint for the client to retrieve that information from the server.
So IMHO, if WWD does not send the event the bug would be in WWD. If the event is sent but LSP4E does not process it, the bug is correct here. I suspect WWD does not send the event. Could you confirm that?

**Comment by jcompagner** [comment]
so WWD (The consumer of LSP4E) is the one calling createProcess() and that also should constantly call:

https://github.com/eclipse/lsp4e/blob/2632a5543974da44ec5ee942823ddf40c67bf104/org.eclipse.lsp4e/src/org/eclipse/lsp4e/progress/LSPProgressManager.java#L161

including an end event, Those events where are they really coming from? is that not the language server itself ?

but anyway what should happen (but then i wouldn't have noticed this) is here:

https://github.com/eclipse/lsp4e/blob/2632a5543974da44ec5ee942823ddf40c67bf104/org.eclipse.lsp4e/src/org/eclipse/lsp4e/progress/LSPProgressManager.java#L114

just before job.schedule() there should be a call job.setSystem(true)

Because i think this is a long running job (at least as long as there are open (ts) files right?)
and those should not constantly be showing up in the UI, that should be hidden away.

**Comment by rubenporras** [comment]
We have the same issue, https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workDoneProgressBegin does not allow to tell if a job is a system job or not, but if the server does not want the client to show the job on the UI, why send the notification at all to begin with?
It still look to me, we need to know which part of WWD is sending the notification and why it is not sending the `WorkDoneProgressEnd`

**Comment by jcompagner** [comment]
no this is purely about Eclipse.. you should not create this as a job in eclipse that is a long running UI job
thats something a the eclipse builder (java compiler) does and so on. 
this job that you make is just a background thing that should do its thing without a user directly knowing it
(at least handling the events)

Maybe that you want to show something to the user based on the events?

But what is the normal flow then? why do you expect the "end" to happen? 

Is that really when the last file is closed? So the language server is shutdown ?
Or is this really some startup thing that quickly sets up when the first file is shown in the editor and before i really starting editing the file the "end" is already send and that background job is finished?

**Comment by jcompagner** [comment]
ah if i read this correctly https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workDoneProgressBegin

then it is really about small tasks.. Like "F3" (open declaration) or "Finding references"

And for me the default title stays there. so i think its not just "end" that is not send but even begin
because begin should set i think the title:

https://github.com/eclipse/lsp4e/blob/2632a5543974da44ec5ee942823ddf40c67bf104/org.eclipse.lsp4e/src/org/eclipse/lsp4e/progress/LSPProgressManager.java#L123

which i think should be seen in the ui...

So it seems createProcess() is called, but then never a notifyProgress()

**Comment by rubenporras** [comment]
The main question is still why there is no notifiyProgress being sent or when is "end" expected to happen. That is not something I can answer, that is something for the one developing WWD.

**Comment by jcompagner** [comment]
seems to be fine to me:

`
[t=1661868825928] LSP4E to org.eclipse.wildwebdeveloper.eslint:
Content-Length: 1652



[t=1661868825928] LSP4E to org.eclipse.wildwebdeveloper.eslint:
{"jsonrpc":"2.0","id":"1","method":"initialize","params":{"processId":11268,"rootPath":"/D:/mytest/test/","rootUri":"file:///D:/mytest/test/","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","delete","rename"],"failureHandling":"undo"},"symbol":{"dynamicRegistration":true},"executeCommand":{"dynamicRegistration":true},"workspaceFolders":true},"textDocument":{"synchronization":{"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"completionItem":{"snippetSupport":true,"documentationFormat":["markdown","plaintext"]}},"hover":{"contentFormat":["markdown","plaintext"]},"signatureHelp":{},"references":{},"documentHighlight":{},"documentSymbol":{"symbolKind":{"valueSet":[18,17,5,14,9,10,22,24,8,1,12,11,20,6,2,3,21,16,19,25,4,7,15,23,26,13]},"hierarchicalDocumentSymbolSupport":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{},"definition":{"linkSupport":true},"typeDefinition":{"linkSupport":true},"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dataSupport":true,"resolveSupport":{"properties":["edit"]},"dynamicRegistration":true},"codeLens":{},"documentLink":{},"colorProvider":{},"rename":{"prepareSupport":true},"foldingRange":{}},"window":{"workDoneProgress":true,"showMessage":{},"showDocument":{"support":true}}},"clientName":"Eclipse SDK","clientInfo":{"name":"Eclipse SDK","version":"0.13.13.202207281726"},"trace":"off","workspaceFolders":[{"uri":"file:///D:/mytest/test/","name":"test"}]}}

[t=1661868825931] LSP4E to org.eclipse.wildwebdeveloper.jsts:
Content-Length: 2028



[t=1661868825931] LSP4E to org.eclipse.wildwebdeveloper.jsts:
{"jsonrpc":"2.0","id":"1","method":"initialize","params":{"processId":11268,"rootPath":"/D:/mytest/test/","rootUri":"file:///D:/mytest/test/","initializationOptions":{"plugins":[{"name":"typescript-plugin-css-modules","location":"C:\\eclipse417\\plugins\\org.eclipse.wildwebdeveloper_0.6.1.202208021414\\node_modules\\typescript-plugin-css-modules"},{"name":"typescript-lit-html-plugin","location":"C:\\eclipse417\\plugins\\org.eclipse.wildwebdeveloper_0.6.1.202208021414\\node_modules\\typescript-lit-html-plugin"}]},"capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","delete","rename"],"failureHandling":"undo"},"symbol":{"dynamicRegistration":true},"executeCommand":{"dynamicRegistration":true},"workspaceFolders":true},"textDocument":{"synchronization":{"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"completionItem":{"snippetSupport":true,"documentationFormat":["markdown","plaintext"]}},"hover":{"contentFormat":["markdown","plaintext"]},"signatureHelp":{},"references":{},"documentHighlight":{},"documentSymbol":{"symbolKind":{"valueSet":[18,17,5,14,9,10,22,24,8,1,12,11,20,6,2,3,21,16,19,25,4,7,15,23,26,13]},"hierarchicalDocumentSymbolSupport":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{},"definition":{"linkSupport":true},"typeDefinition":{"linkSupport":true},"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dataSupport":true,"resolveSupport":{"properties":["edit"]},"dynamicRegistration":true},"codeLens":{},"documentLink":{},"colorProvider":{},"rename":{"prepareSupport":true},"foldingRange":{}},"window":{"workDoneProgress":true,"showMessage":{},"showDocument":{"support":true}}},"clientName":"Eclipse SDK","clientInfo":{"name":"Eclipse SDK","version":"0.13.13.202207281726"},"trace":"off","workspaceFolders":[{"uri":"file:///D:/mytest/test/","name":"test"}]}}

[t=1661868825932] LSP4E to org.eclipse.wildwebdeveloper.angular:
Content-Length: 1652



[t=1661868825932] LSP4E to org.eclipse.wildwebdeveloper.angular:
{"jsonrpc":"2.0","id":"1","method":"initialize","params":{"processId":11268,"rootPath":"/D:/mytest/test/","rootUri":"file:///D:/mytest/test/","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","delete","rename"],"failureHandling":"undo"},"symbol":{"dynamicRegistration":true},"executeCommand":{"dynamicRegistration":true},"workspaceFolders":true},"textDocument":{"synchronization":{"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"completionItem":{"snippetSupport":true,"documentationFormat":["markdown","plaintext"]}},"hover":{"contentFormat":["markdown","plaintext"]},"signatureHelp":{},"references":{},"documentHighlight":{},"documentSymbol":{"symbolKind":{"valueSet":[18,17,5,14,9,10,22,24,8,1,12,11,20,6,2,3,21,16,19,25,4,7,15,23,26,13]},"hierarchicalDocumentSymbolSupport":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{},"definition":{"linkSupport":true},"typeDefinition":{"linkSupport":true},"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dataSupport":true,"resolveSupport":{"properties":["edit"]},"dynamicRegistration":true},"codeLens":{},"documentLink":{},"colorProvider":{},"rename":{"prepareSupport":true},"foldingRange":{}},"window":{"workDoneProgress":true,"showMessage":{},"showDocument":{"support":true}}},"clientName":"Eclipse SDK","clientInfo":{"name":"Eclipse SDK","version":"0.13.13.202207281726"},"trace":"off","workspaceFolders":[{"uri":"file:///D:/mytest/test/","name":"test"}]}}

[t=1661868826325] org.eclipse.wildwebdeveloper.eslint to LSP4E:
{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"ESLint server running in node v16.14.2"}}

[t=1661868826329] org.eclipse.wildwebdeveloper.eslint to LSP4E:
{"jsonrpc":"2.0","id":"1","result":{"capabilities":{"textDocumentSync":{"openClose":true,"change":2,"willSaveWaitUntil":false,"save":{"includeText":false}},"workspace":{"workspaceFolders":{"supported":true}},"codeActionProvider":{"codeActionKinds":["quickfix","source.fixAll.eslint"]},"executeCommandProvider":{"commands":["eslint.applySingleFix","eslint.applySuggestion","eslint.applySameFixes","eslint.applyAllFixes","eslint.applyDisableLine","eslint.applyDisableFile","eslint.openRuleDoc"]}}}}

[t=1661868826330] LSP4E to org.eclipse.wildwebdeveloper.eslint:
Content-Length: 52



[t=1661868826330] LSP4E to org.eclipse.wildwebdeveloper.eslint:
{"jsonrpc":"2.0","method":"initialized","params":{}}

[t=1661868826331] LSP4E to org.eclipse.wildwebdeveloper.eslint:
Content-Length: 156



[t=1661868826331] LSP4E to org.eclipse.wildwebdeveloper.eslint:
{"jsonrpc":"2.0","method":"workspace/didChangeWorkspaceFolders","params":{"event":{"added":[{"uri":"file:///D:/mytest/test/","name":"test"}],"removed":[]}}}

[t=1661868826331] LSP4E to org.eclipse.wildwebdeveloper.eslint:
Content-Length: 446



[t=1661868826331] LSP4E to org.eclipse.wildwebdeveloper.eslint:
{"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///D:/mytest/test/src/app/app.component.ts","languageId":"ts","version":1,"text":"import { Component } from \u0027@angular/core\u0027;\n\n@Component({\n  selector: \u0027app-root\u0027,\n  templateUrl: \u0027./app.component.html\u0027,\n  styleUrls: [\u0027./app.component.css\u0027]\n})\nexport class AppComponent {\n  title \u003d \u0027test\u0027;\n}\n"}}}

[t=1661868826332] org.eclipse.wildwebdeveloper.eslint to LSP4E:
{"jsonrpc":"2.0","id":0,"method":"client/registerCapability","params":{"registrations":[{"id":"6da2e347-9c1b-45ae-bb26-7020c731fdb7","method":"workspace/didChangeConfiguration","registerOptions":{}}]}}

[t=1661868826332] org.eclipse.wildwebdeveloper.eslint to LSP4E:
{"jsonrpc":"2.0","id":1,"method":"client/registerCapability","params":{"registrations":[{"id":"93856ffe-285f-4686-baaf-45130d9d20a0","method":"workspace/didChangeWorkspaceFolders","registerOptions":{}}]}}

[t=1661868826332] LSP4E to org.eclipse.wildwebdeveloper.eslint:
Content-Length: 38



[t=1661868826332] LSP4E to org.eclipse.wildwebdeveloper.eslint:
{"jsonrpc":"2.0","id":0,"result":null}

[t=1661868826332] LSP4E to org.eclipse.wildwebdeveloper.eslint:
Content-Length: 38



[t=1661868826332] LSP4E to org.eclipse.wildwebdeveloper.eslint:
{"jsonrpc":"2.0","id":1,"result":null}

[t=1661868826333] org.eclipse.wildwebdeveloper.eslint to LSP4E:
{"jsonrpc":"2.0","id":2,"method":"workspace/configuration","params":{"items":[{"scopeUri":"file:///D:/mytest/test/src/app/app.component.ts","section":""}]}}

[t=1661868826334] LSP4E to org.eclipse.wildwebdeveloper.eslint:
Content-Length: 326



[t=1661868826334] LSP4E to org.eclipse.wildwebdeveloper.eslint:
{"jsonrpc":"2.0","id":2,"result":[{"rulesCustomizations":[],"nodePath":"D:\\mytest\\test","codeAction":{"showDocumentation":{"enable":"true"},"disableRuleComment":{"location":"separateLine","enable":"true"}},"workspaceFolder":{"uri":"file:/D:/mytest/test/"},"run":"onType","workingDirectory":{"mode":"auto"},"validate":"on"}]}

[t=1661868826452] org.eclipse.wildwebdeveloper.eslint to LSP4E:
{"jsonrpc":"2.0","id":3,"method":"eslint/noLibrary","params":{"source":{"uri":"file:///D:/mytest/test/src/app/app.component.ts"}}}

[t=1661868826452] LSP4E to org.eclipse.wildwebdeveloper.eslint:
Content-Length: 38



[t=1661868826452] LSP4E to org.eclipse.wildwebdeveloper.eslint:
{"jsonrpc":"2.0","id":3,"result":null}

[t=1661868826582] org.eclipse.wildwebdeveloper.angular to LSP4E:
{"jsonrpc":"2.0","id":"1","result":{"capabilities":{"codeLensProvider":{"resolveProvider":true},"textDocumentSync":2,"completionProvider":{"resolveProvider":true,"triggerCharacters":["<",".","*","[","(","$","|"]},"definitionProvider":true,"typeDefinitionProvider":true,"referencesProvider":true,"renameProvider":{"prepareProvider":true},"hoverProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",","],"retriggerCharacters":[","]},"workspace":{"workspaceFolders":{"supported":true}}},"serverOptions":{}}}

[t=1661868826583] LSP4E to org.eclipse.wildwebdeveloper.angular:
Content-Length: 52



[t=1661868826583] LSP4E to org.eclipse.wildwebdeveloper.angular:
{"jsonrpc":"2.0","method":"initialized","params":{}}

[t=1661868826584] LSP4E to org.eclipse.wildwebdeveloper.angular:
Content-Length: 156



[t=1661868826584] LSP4E to org.eclipse.wildwebdeveloper.angular:
{"jsonrpc":"2.0","method":"workspace/didChangeWorkspaceFolders","params":{"event":{"added":[{"uri":"file:///D:/mytest/test/","name":"test"}],"removed":[]}}}

[t=1661868826584] LSP4E to org.eclipse.wildwebdeveloper.angular:
Content-Length: 446



[t=1661868826584] LSP4E to org.eclipse.wildwebdeveloper.angular:
{"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///D:/mytest/test/src/app/app.component.ts","languageId":"ts","version":1,"text":"import { Component } from \u0027@angular/core\u0027;\n\n@Component({\n  selector: \u0027app-root\u0027,\n  templateUrl: \u0027./app.component.html\u0027,\n  styleUrls: [\u0027./app.component.css\u0027]\n})\nexport class AppComponent {\n  title \u003d \u0027test\u0027;\n}\n"}}}

[t=1661868826598] org.eclipse.wildwebdeveloper.jsts to LSP4E:
{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"[lspserver] Using Typescript version (workspace) 4.7.4 from path \"d:\\mytest\\test\\node_modules\\typescript\\lib\\tsserver.js\""}}

[t=1661868827175] org.eclipse.wildwebdeveloper.jsts to LSP4E:
{"jsonrpc":"2.0","id":"1","result":{"capabilities":{"textDocumentSync":2,"completionProvider":{"triggerCharacters":[".","\"","'","/","@","<"],"resolveProvider":true},"codeActionProvider":{"codeActionKinds":["source.fixAll.ts","source.removeUnused.ts","source.addMissingImports.ts","source.organizeImports.ts"]},"definitionProvider":true,"documentFormattingProvider":true,"documentRangeFormattingProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"executeCommandProvider":{"commands":["_typescript.applyWorkspaceEdit","_typescript.applyCodeAction","_typescript.applyRefactoring","_typescript.organizeImports","_typescript.applyRenameFile"]},"hoverProvider":true,"renameProvider":true,"referencesProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",",","<"]},"workspaceSymbolProvider":true,"implementationProvider":true,"typeDefinitionProvider":true,"foldingRangeProvider":true,"semanticTokensProvider":{"documentSelector":null,"legend":{"tokenTypes":["class","enum","interface","namespace","typeParameter","type","parameter","variable","enumMember","property","function","member"],"tokenModifiers":["declaration","static","async","readonly","defaultLibrary","local"]},"full":true,"range":true},"callsProvider":true}}}

[t=1661868827177] LSP4E to org.eclipse.wildwebdeveloper.jsts:
Content-Length: 52



[t=1661868827177] LSP4E to org.eclipse.wildwebdeveloper.jsts:
{"jsonrpc":"2.0","method":"initialized","params":{}}

[t=1661868827177] LSP4E to org.eclipse.wildwebdeveloper.angular:
Content-Length: 143



[t=1661868827177] LSP4E to org.eclipse.wildwebdeveloper.angular:
{"jsonrpc":"2.0","id":"2","method":"textDocument/codeLens","params":{"textDocument":{"uri":"file:///D:/mytest/test/src/app/app.component.ts"}}}

[t=1661868827178] LSP4E to org.eclipse.wildwebdeveloper.jsts:
Content-Length: 446



[t=1661868827178] LSP4E to org.eclipse.wildwebdeveloper.jsts:
{"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///D:/mytest/test/src/app/app.component.ts","languageId":"ts","version":1,"text":"import { Component } from \u0027@angular/core\u0027;\n\n@Component({\n  selector: \u0027app-root\u0027,\n  templateUrl: \u0027./app.component.html\u0027,\n  styleUrls: [\u0027./app.component.css\u0027]\n})\nexport class AppComponent {\n  title \u003d \u0027test\u0027;\n}\n"}}}

[t=1661868827178] LSP4E to org.eclipse.wildwebdeveloper.jsts:
Content-Length: 147



[t=1661868827178] LSP4E to org.eclipse.wildwebdeveloper.jsts:
{"jsonrpc":"2.0","id":"2","method":"textDocument/foldingRange","params":{"textDocument":{"uri":"file:///D:/mytest/test/src/app/app.component.ts"}}}

[t=1661868827178] LSP4E to org.eclipse.wildwebdeveloper.jsts:
Content-Length: 188



[t=1661868827178] LSP4E to org.eclipse.wildwebdeveloper.jsts:
{"jsonrpc":"2.0","id":"3","method":"textDocument/documentHighlight","params":{"textDocument":{"uri":"file:///D:/mytest/test/src/app/app.component.ts"},"position":{"line":0,"character":0}}}

[t=1661868827188] org.eclipse.wildwebdeveloper.jsts to LSP4E:
{"jsonrpc":"2.0","id":0,"method":"window/workDoneProgress/create","params":{"token":"747a4f88-116d-40e8-be22-37d54b3d67d2"}}

[t=1661868827188] LSP4E to org.eclipse.wildwebdeveloper.jsts:
Content-Length: 38



[t=1661868827188] LSP4E to org.eclipse.wildwebdeveloper.jsts:
{"jsonrpc":"2.0","id":0,"result":null}

[t=1661868827189] org.eclipse.wildwebdeveloper.jsts to LSP4E:
{"jsonrpc":"2.0","method":"$/progress","params":{"token":"747a4f88-116d-40e8-be22-37d54b3d67d2","value":{"kind":"begin","title":"Initializing JS/TS language featuresâ€¦"}}}

[t=1661868827214] LSP4E to org.eclipse.wildwebdeveloper.jsts:
Content-Length: 149



[t=1661868827214] LSP4E to org.eclipse.wildwebdeveloper.jsts:
{"jsonrpc":"2.0","id":"4","method":"textDocument/documentSymbol","params":{"textDocument":{"uri":"file:///D:/mytest/test/src/app/app.component.ts"}}}

[t=1661868827716] LSP4E to org.eclipse.wildwebdeveloper.jsts:
Content-Length: 64



[t=1661868827716] LSP4E to org.eclipse.wildwebdeveloper.jsts:
{"jsonrpc":"2.0","method":"$/cancelRequest","params":{"id":"4"}}

[t=1661868827716] LSP4E to org.eclipse.wildwebdeveloper.jsts:
Content-Length: 149



[t=1661868827716] LSP4E to org.eclipse.wildwebdeveloper.jsts:
{"jsonrpc":"2.0","id":"5","method":"textDocument/documentSymbol","params":{"textDocument":{"uri":"file:///D:/mytest/test/src/app/app.component.ts"}}}

[t=1661868828740] org.eclipse.wildwebdeveloper.angular to LSP4E:
{"jsonrpc":"2.0","method":"angular/projectLoadingStart","params":[null]}

[t=1661868828740] org.eclipse.wildwebdeveloper.angular to LSP4E:
{"jsonrpc":"2.0","method":"angular/projectLoadingFinish","params":[null]}

[t=1661868828740] org.eclipse.wildwebdeveloper.angular to LSP4E:
{"jsonrpc":"2.0","method":"angular/projectLanguageService","params":{"projectName":"d:/mytest/test/tsconfig.json","languageServiceEnabled":false}}

[t=1661868828740] org.eclipse.wildwebdeveloper.angular to LSP4E:
{"jsonrpc":"2.0","id":0,"method":"window/workDoneProgress/create","params":{"token":"fc806ee9-1633-4a56-bfb1-049e4cb9ef61"}}

[t=1661868828740] LSP4E to org.eclipse.wildwebdeveloper.angular:
Content-Length: 38



[t=1661868828740] LSP4E to org.eclipse.wildwebdeveloper.angular:
{"jsonrpc":"2.0","id":0,"result":null}

[t=1661868828741] org.eclipse.wildwebdeveloper.angular to LSP4E:
{"jsonrpc":"2.0","id":"2","result":null}

[t=1661868828750] org.eclipse.wildwebdeveloper.angular to LSP4E:
{"jsonrpc":"2.0","method":"$/progress","params":{"token":"fc806ee9-1633-4a56-bfb1-049e4cb9ef61","value":{"kind":"begin","title":"Angular","message":"Running ngcc for d:/mytest/test/tsconfig.json"}}}

[t=1661868830383] org.eclipse.wildwebdeveloper.jsts to LSP4E:
{"jsonrpc":"2.0","method":"$/progress","params":{"token":"747a4f88-116d-40e8-be22-37d54b3d67d2","value":{"kind":"end"}}}

[t=1661868830391] org.eclipse.wildwebdeveloper.jsts to LSP4E:
{"jsonrpc":"2.0","id":"2","result":[{"startLine":2,"endLine":6},{"startLine":2,"endLine":5},{"startLine":5,"endLine":5},{"startLine":7,"endLine":8}]}

[t=1661868830410] org.eclipse.wildwebdeveloper.jsts to LSP4E:
{"jsonrpc":"2.0","id":"3","result":[]}

[t=1661868830411] org.eclipse.wildwebdeveloper.jsts to LSP4E:
{"jsonrpc":"2.0","id":"4","result":[{"name":"AppComponent","detail":"","kind":5,"range":{"start":{"line":2,"character":0},"end":{"line":9,"character":1}},"selectionRange":{"start":{"line":7,"character":13},"end":{"line":7,"character":25}},"children":[{"name":"title","detail":"","kind":7,"range":{"start":{"line":8,"character":2},"end":{"line":8,"character":17}},"selectionRange":{"start":{"line":8,"character":2},"end":{"line":8,"character":7}},"children":[]}]}]}

[t=1661868830413] org.eclipse.wildwebdeveloper.jsts to LSP4E:
{"jsonrpc":"2.0","id":"5","result":[{"name":"AppComponent","detail":"","kind":5,"range":{"start":{"line":2,"character":0},"end":{"line":9,"character":1}},"selectionRange":{"start":{"line":7,"character":13},"end":{"line":7,"character":25}},"children":[{"name":"title","detail":"","kind":7,"range":{"start":{"line":8,"character":2},"end":{"line":8,"character":17}},"selectionRange":{"start":{"line":8,"character":2},"end":{"line":8,"character":7}},"children":[]}]}]}

[t=1661868830520] org.eclipse.wildwebdeveloper.jsts to LSP4E:
{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///D:/mytest/test/src/app/app.component.ts","diagnostics":[]}}

[t=1661868830805] org.eclipse.wildwebdeveloper.angular to LSP4E:
{"jsonrpc":"2.0","method":"angular/NgccProgressEnd","params":{"configFilePath":"d:/mytest/test/tsconfig.json"}}

[t=1661868830805] org.eclipse.wildwebdeveloper.angular to LSP4E:
{"jsonrpc":"2.0","method":"$/progress","params":{"token":"fc806ee9-1633-4a56-bfb1-049e4cb9ef61","value":{"kind":"end"}}}

[t=1661868830805] org.eclipse.wildwebdeveloper.angular to LSP4E:
{"jsonrpc":"2.0","method":"angular/projectLanguageService","params":{"projectName":"d:/mytest/test/tsconfig.json","languageServiceEnabled":true}}

[t=1661868831334] org.eclipse.wildwebdeveloper.angular to LSP4E:
{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///d%3A/mytest/test/src/app/app.component.ts","diagnostics":[]}}
`

i see 2 being created 1 is that i see poping up and going away:


{"jsonrpc":"2.0","id":0,"method":"window/workDoneProgress/create","params":{"token":"747a4f88-116d-40e8-be22-37d54b3d67d2"}}
{"jsonrpc":"2.0","method":"$/progress","params":{"token":"747a4f88-116d-40e8-be22-37d54b3d67d2","value":{"kind":"begin","title":"Initializing JS/TS language featuresâ€¦"}}}
{"jsonrpc":"2.0","method":"$/progress","params":{"token":"747a4f88-116d-40e8-be22-37d54b3d67d2","value":{"kind":"end"}}}


and that title i really also see.

then the other:

{"jsonrpc":"2.0","id":0,"method":"window/workDoneProgress/create","params":{"token":"fc806ee9-1633-4a56-bfb1-049e4cb9ef61"}}
{"jsonrpc":"2.0","method":"$/progress","params":{"token":"fc806ee9-1633-4a56-bfb1-049e4cb9ef61","value":{"kind":"begin","title":"Angular","message":"Running ngcc for d:/mytest/test/tsconfig.json"}}}
{"jsonrpc":"2.0","method":"$/progress","params":{"token":"fc806ee9-1633-4a56-bfb1-049e4cb9ef61","value":{"kind":"end"}}}

and that title i even don't see, so it seems to create it but then no interaction at all with it..

**Comment by jcompagner** [comment]
hmmmm

https://github.com/eclipse/wildwebdeveloper/blob/master/org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/angular/AngularClientImpl.java#L52

i think have a custom impl of that notify because it was not really implemented first in LSP4E ??
and because of that nothing ends up now in the correct place?

**Comment by rubenporras** [comment]
that makes sense, I see `notifyProgress` has been overridden, but not `createProgress`.  It would also explain why it happens only for the "Angular" client. Most probably if you override `createProgress` to do nothing, the issue is solved.

**Comment by jcompagner** [comment]
i think we should do the other way around ;)

delete the notifyProgress  and let lsp4e do everything now

i think that method was added 2 years ago because the angular client would constantly say things like "unsupported event" and so on, so the angular client did get some basic implementations. 
But now the core supports it so i thin we should just remove as much as possible...

**Comment by rubenporras** [comment]
I would do that as well if the feature is useful for you. I am happy if it would be useful. Shall we close the ticket?

**Comment by mickaelistria** [comment]
Thanks for the analysis @jcompagner ; please consider opening a PR that would fix it on Wild Web Developer end as you suggested a couple of comments ago.
