### ISSUE TITLE
Missing user feedback when on save actions timeout and timeout is too small

### ISSUE THREAD

**Issue by rubenporras** [eclipse/lsp4e#216]
We currently have no user feedback when on save actions timeout and the timeout is too small (just 2secs).

The proposal is to:
* increase the timeout to 10secs 
* add a pop-up dialog if the timeout is reached explaining what happen and pointing the user to the preference page where he can
* change the timeout or suppress the pop-up

**Comment by mickaelistria** [comment]
Do save action freeze the editor? If so a 10s timeout would be too extreme.
A popup is extremely annoying.
A notification (vanishing popup on the bottom right corner) would be a good cimpromise.

**Comment by rubenporras** [comment]
I also think pop-ups are very annoying but I did not know we could do vanishing notifications. That is much better. 
I have set the default timeout to five secs
