### ISSUE TITLE
LSPFormatHandler.execute() does not wait for the format request, might trash the editor contents

### ISSUE THREAD

**Issue by rubenporras** [eclipse/lsp4e#219]
Since LSPFormatHandler.execute() does not wait for the format request blocking the editor and there is no visual feedback that the system is executing a format action, if the user types while format is being processed, once the format request comes back, the async method

```
				formatter.requestFormatting(document, (ITextSelection) selection).thenAcceptAsync(
						edits -> shell.getDisplay().asyncExec(() -> formatter.applyEdits(document, edits)));

```

will apply the edits which came back from the formatter, and either throw BadLocationException or trash the content or the editor buffer (by replacing existing regions which are modified with the contents returned by the formatter).

**Comment by rubenporras** [comment]
@mickaelistria , I suggest, that to solve the issue, the editor should wait before applying the edits by using `thenAccept` instead of `thenAcceptAsync` or get the future using a timeout and discarding the answer if the timeout is exceeded.

Since here the user manually requests formatting, I think the timeout can be high, so to me using `thenAccept` is just fine. What do you think?

**Comment by mickaelistria** [comment]
I believe that wouldn't be enough: it's very possible that `requestFormatting` takes a lot of time, and editor isn't frozen during that time and user can change content in the meantime. Using thenAccept wouldn't block the editor either.
I believe we really need a way to explicitly lock the document or the viewer here; and to unlock it upon completaion or failure.
