### ISSUE TITLE
"workspace/didChangeWorkspaceFolders" not triggered on workspace projects change

### ISSUE THREAD

**Issue by michelkaporin** [eclipse/lsp4e#226]
When adding or closing an Eclipse project, `workspace/didChangeWorkspaceFolders` notification is not being sent. 

[Current implementation](https://github.com/eclipse/lsp4e/blob/5d7e4a6ddcc88b51964ad3c00743be9d171f2d57/org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java#L556) doesn't seem to be enough to post updates.

**Comment by mickaelistria** [comment]
Would you be willing to submit a full request that fixes it? It would be also relatively easy to add a test case for it in existing WorkspaceFoldersTest.java

**Comment by michelkaporin** [comment]
Couldn't reproduce this with LSP4E code and found a bug in the sever implementation. It wasn't announcing sever capability correctly. Closing as not relevant, thanks!
