### ISSUE TITLE
Question: LSP4E with Linked Files

### ISSUE THREAD

**Issue by rubenporras** [eclipse/lsp4e#23]
Hi,

in our implementation, LSP4e would need to deal with eclipse projects which has linked files, which are not visible in the OS filesystem, they are only visible in our custom eclipse filesystem.

I think that since the files are not on the OS filesystem, the Language Server (an Xtext one) cannot discover them. It only discovers the files as I open them, but not the rest of the workspace.

I was thinking on notifying the language server manually that files are added to our custom eclipse filesystem, with some code similar to the following:

        try {
          LanguageServiceAccessor.getInitializedLanguageServers(file, x -> true);
        } catch (IOException e) {
          LOGGER.error(e);
        }

I have noticed that I get warnings because LanguageServiceAccessor is marked as private API, and Eclipse warns me about that.

Thus I have the following questions:

•	Is there a better way to access the Language Server and manually connect files? If not, shall I just use this code and supress the warning?
•	Does it make sense what I try to achieve, that is, manually sending to the Language Server the list of files which are in the project?  If not, what would be the recommened approach?

Cheers

**Comment by mickaelistria** [comment]
The assumption is usually that the LS can access the same resources as the client. Virtual filesystems or linked files make this assumption broken, so it's even not clear that language servers are supposed to work at all with them.
However, you can trick the filesystem consumers with symbolic link or linked files on the filesystem level (instead of client one). Is this something you can use?

**Comment by rubenporras** [comment]
Is the assumption that the LS can access the same resources as the client is something built into the LSP Specification (I could not find it) or rather something built-in LSP4e? 

I see that the client includes the source text in the Json, request, so fetching the text of the source does not require that the server can access the source on the filesystem level. I also found in https://microsoft.github.io/language-server-protocol/specification#workspace_didChangeWatchedFiles that "Servers are allowed to run their own file system watching mechanism and not rely on clients to provide file system events. However this is not recommended", so I am not sure how to understand the assumption.

I am not sure what we would need to use symbolic link or linked files on the filesystem level but so far I did not detected any problem with the virtual file system. Yes, I needed to submit a couple of changes to the LSPEclipseUtils class, but so far the changes where not complex or cumbersome.

We have a highly customized eclipse and xtext setup already (I would not go into details), so even if I prefer that LSP4e works out of the box as much as possible, if we need to customize/extend it little LSP4e, it would not be a deal breaker for us. With this in mind calling LanguageServiceAccessor.getInitializedLanguageServers(file, x -> true); does not seem to be a big issue. Or do you know already about any problem with that?

**Comment by mickaelistria** [comment]
If symbolic links can't work, then yes, you probably have to notify the LS about all the files existing an their content so it can re-emulate the filesystem on its end.

> calling LanguageServiceAccessor.getInitializedLanguageServers(file, x -> true); does not seem to be a big issue. Or do you know already about any problem with that?

No, that's not a problem, some other LSP4E clients do it already.

**Comment by rubenporras** [comment]
Thanks for the quick answer, then I close the ticket and carry on with the call as in my first comment when opening the ticket.
