### ISSUE TITLE
F3 - open definition seems weired after upgrade

### ISSUE THREAD

**Issue by leomayer** [eclipse/lsp4e#25]
I tried to update my Eclipse like mentioned in eclipse/wildwebdeveloper#731. I'm not really sure if the upgrade completely succeeded. Nevertheless just want to be on the save side with the annoyance of the new function to `open definitions`.

Running eclipse.buildId=4.21.0.I20210906-0500

When I press F3 - to open the definition I get the attached menu. I understand the menu to some extend - but to some extent not. To my understanding it should be only the second and/or the fourth entry. The rest seems superfluous. If there would be only one entry of that kind - just open this one. 
![Bildschirmfoto von 2021-11-09 09-45-07](https://user-images.githubusercontent.com/2641128/140892727-8bdb15a6-c4ca-4f62-9e79-9d5eb243ce3b.png)

Any ideas? 

BTW: The keybinding seems as mess in the new Eclipse since a binding to CTRL-SHIFT-8 does NOT work with non English keyboards!!!

**Comment by leomayer** [comment]
Well to say it honestly: till 2021-09 I did jump directly into the source code. With the upgrade to 2021-12 I get this list of items which I don't know what to do with them.
Why should I jump to the type declaration? Give me one reason for it... I only want the definition of what's under F3 - either method or if not available the e.g. Enum definition - same style as Java does it.

**Comment by mickaelistria** [comment]
The reason why there are now more proposals is that the language server used by Wild Web Developer is now richer and is capable of returning Type Declarations as well; which can sometimes be useful to navigate to (but not always).
F3 is defined in the editor. The Generic Editor (coming from Eclipse Platform) does keep the default behavior for F3, which is showing all proposals. The `doOperation` method in Generic Editor should be overriden so that the `OPEN_HYPERLINK` action directly opens 1st link without showing the proposals.

**Comment by nitind** [comment]
Is there a way to disambiguate the results so that F3 always opens the definition as the user expects? Always opening the first one may be more consistent, but it could be consistently wrong.

**Comment by mickaelistria** [comment]
Current code in LSP4E is expected to return first the result of `textDocument/definition` and then the result of `textDocument/typeDefinition`, so we can hope they'd be consistently right for the LSP4E part at least.

**Comment by leomayer** [comment]
So here is the log [org.eclipse.wildwebdeveloper.jsts-copy.log](https://github.com/eclipse/lsp4e/files/7733419/org.eclipse.wildwebdeveloper.jsts-copy.log) for the following screenshot

![Bildschirmfoto von 2021-12-17 08-39-14](https://user-images.githubusercontent.com/2641128/146508469-6c41d7fe-fa6f-4a25-8d68-667990b8f904.png)

As you can see in the logs the order is:

- empty
- textDocument/documentHighlight
- textDocument/hover
- textDocument/definition
- textDocument/typeDefinition

==> Somehow I have troubles to follow the arguments. My log looks different (I already posted my config above). But when I now open a ticket with TSLS I have trouble for references what is a bug and what not. 

Nevertheless I would like to open with F3 `textDocument/definition` as it was in the previous versions - despite what LSP4E returns.

**Comment by mickaelistria** [comment]
> Nevertheless I would like to open with F3 textDocument/definition as it was in the previous versions - despite what LSP4E returns.

That's a wrong understanding. F3 has never been textDocument/definition, it's just that in previous versions, the language server was not returning any typeDefinition, so there was only 1 hyperlink (output of textDocument/definition) which was then open automatically as there was no other choice.

**Comment by leomayer** [comment]
Yeah, fine. Its good to understand the situation and the reasons from your perspective as a developer. Nevertheless from a users perspective I insist in opening `textDocument/definition`. I have no clue what to do with the other 3 options and how they are wired  internally. Especially since the externally open a file, open the elcipse market place, etc.etc.

> Current code in LSP4E is expected to return first the result of `textDocument/definition` and then the result of `textDocument/typeDefinition`, 

From a developer point of view I'm surprised that you trust on the order of entries instead of key-value pairs. The order could be arbitrary.

**Comment by mickaelistria** [comment]
Upstream issue is https://bugs.eclipse.org/bugs/show_bug.cgi?id=577865 . There is nothing to change in LSP4E here, so we can close.

**Comment by leomayer** [comment]
Sorry but even the ticket will be fulfilled the way you've opened it - it still leaves unclear why the first entry has to be `textDocument/definition`. If this is the requirement than I would guess its also a ticket against the Typescript-Language-Server. Who else should grant that this is the very first entry?

**Comment by mickaelistria** [comment]
You may be right. The way code is written doesn't ensure `textDocument/definition` is sent first and that its results are shown first; although I suspect that the synchronization that's in place kind of guarantees that the request is sent first at least. Code may be improved to fix that; however, it's diverging from initial issue.
If you can reproduce a situation where the typeDefinition results are shown before the definition one with Ctrl+Hover, please open a separate issue and then we'll have concrete matter to reword to code to guarantee an order.

**Comment by leomayer** [comment]
Only for correct understanding: Open a new ticket for granting the proper order - IFF I can reproduce a situation? The log-files I've attached today are not sufficient? If so, what is missing?
