### ISSUE TITLE
Support detail information in Outline View

### ISSUE THREAD

**Issue by gerdleon** [eclipse/lsp4e#250]
The LSP protocol allows the optional string "detail" in the "[DocumentSymbol](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#documentSymbol)".

When testing with the Outline View detail information was not shown. Only Symbol.kind and Symbol.name are shown. 

We could create a patchset to implement the support - unless someone else is already working on it. 
What do you think?

**Comment by mickaelistria** [comment]
Such a contribution would be welcome!

**Comment by gerdleon** [comment]
Hi Mickael,
Is it ok to remove the textual showing of the SymbolKind? It is already indicated by the icon and, I think, it would clash with the showing of the details. 
I cross-checked the outline in VS Code and it does not have an option to show the SymbolKind as text.

**Comment by mickaelistria** [comment]
Yes, I believe it would be fine.
