### ISSUE TITLE
Two CodeMiningReconciler are created for one file

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lsp4e#273]
When you open a file like JSON, I noticed that there are 2 CodeMiningReconciler which are installed which is very annoying since codemining can be expensive.

The reason about those 2 CodeMiningReconciler is that it is declared in generic editor plugin and lsp4e plugin. I think LSP4e should remove the declaration of code mining provider.

**Comment by sebthom** [comment]
@mickaelistria I can confirm that two instances are created. Any reason to not remove the CodeMiningReconciler from LSP4E?

**Comment by mickaelistria** [comment]
> Any reason to not remove the CodeMiningReconciler from LSP4E?

Not that I remember. Removing it sounds like a good idea.
