### ISSUE TITLE
Add support for Semantic Tokens

### ISSUE THREAD

**Issue by bknaysi** [eclipse/lsp4e#274]
Hi,

We are very interested in using semantic tokens to supplement or replace TextMate coloring all together. Is there any plan to implement client support for this feature?

https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_semanticTokens

Thanks,
Bradley

**Comment by rubenporras** [comment]
Hi @bknaysi , see https://github.com/eclipse/lsp4e/pull/253

**Comment by jnt0r** [comment]
I tried to use this feature in an Eclipse plugin but it does not work for me. I only get highlighting for strings and numbers but nothing else. The same LSP provides semantic tokens in VSCode and other IDEs. 
Do I need to enable this feature in any way or should it be available out of the box? The documentation and readme do not yet list this as a supported feature.

**Comment by mickaelistria** [comment]
Which version of LSP4E are you using? Have you tried latest snapshot build?
You can check the language server logs (to enable in preference) and verify that the proper capabilities are sent and whether the tokens are passed from server to client.

**Comment by jnt0r** [comment]
I'm using Eclipse 2023-09 which bundles lsp4e 0.17.1.
I can see the tokens sent from the server to the client in the logs.

**Comment by jnt0r** [comment]
No, I don't habe a TextMate grammar. I thought I would replace TextMate with the semantic tokens from the LSP as in VSCode. Is there any documentation or working example for this? I would really like to get my files colored :)

**Comment by mickaelistria** [comment]
> No, I don't have a TextMate grammar. I thought I would replace TextMate with the semantic tokens from the LSP as in VSCode.

I agree it is the goal.

> I think that the current solution takes for granted that you have setup TexMate grammar using TM4E for your language, have you done that?

is a grammar really necessary? I would also expect that only the *theme* would be used to remap tokens to text colors and style.

**Comment by rubenporras** [comment]
> No, I don't have a TextMate grammar. I thought I would replace TextMate with the semantic tokens from the LSP as in VSCode.
> I agree it is the goal.

I am not sure. Semantic highlight information should come from the server, but if possible syntactic one should come from the client, just because it is faster to do so. The protocol also says (I think the word **additional** is important): 

> Semantic tokens are used to add **additional** color information to a file that depends on language specific symbol information. A semantic token request usually produces a large result

The documentation of `SemanticHighlightReconcilerStrategy` says as well that the class works as listener to presentation changes:

>  This strategy applies semantic highlight on top of the syntactic highlight provided by TM4E by implementing {@link ITextPresentationListener}. Because semantic highlight involves remote calls, it is expected to be slower than syntactic highlight. Thus we execute semantic highlight processing in a separate reconciler thread that will never block TM4E.

We could find a way to implement semantic highlight without syntactic one, but it was not the intention of the current code.

**Comment by jnt0r** [comment]
Do you have a working example with semantic tokens?

I agree, that it is additional but it should not depend on the grammar being present. Visual Studio Code can also highlight semantic tokens without specifying a grammar.

**Comment by jnt0r** [comment]
That would take some time but I could take a look into it in a few weeks.

**Comment by rubenporras** [comment]
I agree it would be welcome if you could make it work also for the cases where syntax highlight is not available. Just in case it helps, the easiest implementation (yet maybe weird) would be an optional reconciler that sets an _empty_ text presentation. Then the current semantic highlight reconciler would participate in the process and add the semantic highlight.

**Comment by jnt0r** [comment]
I might just figured out, that the semantic tokens override the textmate grammar and it also works without a grammar even specified. But the tokens used by the LSP seem to not be recognized so they have no special color.

**Comment by rubenporras** [comment]
I have forgotten this detail, but yes, that is right. See org.eclipse.lsp4e.operations.semanticTokens.TokenTypeMapper, it uses TM4E themes. Maybe if you can configure a TM4E theme with the names of your tokens, it would just do what you need.

**Comment by jnt0r** [comment]
Is there a bug in TokenTypeMapper? Shouldn't it return the Token from the TokenProvider? Currently the return value is just ignored:
https://github.com/eclipse/lsp4e/blob/32fd6631496271cf95031d12ecaa44b558b6006d/org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/semanticTokens/TokenTypeMapper.java#L39-L45

**Comment by rubenporras** [comment]
> Is there a bug in TokenTypeMapper? Shouldn't it return the Token from the TokenProvider? Currently the return value is just ignored:

Yes, it looks very much like that. Could you create a PR?

**Comment by jnt0r** [comment]
@rubenporras https://github.com/eclipse/lsp4e/pull/815

**Comment by jnt0r** [comment]
I can now confirm that by defining a theme with a css file i get semantic highlighting with only the lsp. I'm using the newest snapshot build.

**Comment by jnt0r** [comment]
Should we open another issue to track the fact that the LSP tokens are not recognized? I think it is not convenient to require every user to define the same theme with the same tokens. There we could discuss how to implement this.
