### ISSUE TITLE
Eclipse crash with MacOS 13.0 on Intel x64

### ISSUE THREAD

**Issue by sgjohnston** [eclipse/lsp4e#276]
I am not certain if this issue belongs in lsp4e, and any guidance on reassigning would be welcome if not. The problem is with an Intel x64 Mac running MacOS 13.0: when using WildWebDeveloper with the language server "JavaScript-TypeScript Language Server" enabled, any operation in a JavaScript file, even just hovering the mouse over a definition, will immediately crash Eclipse. We have two Macs, one Intel x64 and one Apple Silicon, and this only occurs with the Intel x64 processor. From the stack trace, it looks like Eclipse is calling into Apple WebCore when this happens.

Disabling the JS-TS language server stops the problem occurring (it is OK to leave eslint enabled). It's difficult to really understand what is happening, although it is extremely easy to reproduce on our system. We have tried with a fresh Eclipse installation, etc.

LSP4J installed: 	`Eclipse LSP4J	org.eclipse.lsp4j	0.15.0.v20220805-0131	org.eclipse.lsp4j`
WildWebDevelopor: `Eclipse Wild Web Developer project	Wild Web Developer: web development in Eclipse IDE	0.6.0.202206151321	org.eclipse.wildwebdeveloper`
Node (embedded): `Eclipse Wild Web Developer	Node.js for MacOS x64	0.1.8.202205271506	org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64`

Stack trace from Mac crash report:

`Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [3501]

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   ???                           	    0x3c87daae811f ???
1   ???                           	    0x3c87daa66251 ???
2   ???                           	    0x3c87daa61440 ???
3   ???                           	    0x3c87daa6b48b ???
4   ???                           	    0x3c87daa54dbf ???
5   ???                           	    0x3c87daa4c594 ???
6   ???                           	    0x3c87daa6b7cb ???
7   ???                           	    0x3c87daa54dbf ???
8   ???                           	    0x3c87daa4c39a ???
9   JavaScriptCore                	    0x7ff82ec8e3b8 llint_entry + 119182
10  JavaScriptCore                	    0x7ff82ec8e3b8 llint_entry + 119182
11  JavaScriptCore                	    0x7ff82ec8e3b8 llint_entry + 119182
12  JavaScriptCore                	    0x7ff82ec8e3b8 llint_entry + 119182
13  ???                           	    0x3c87daa4c39a ???
14  JavaScriptCore                	    0x7ff82ec8e3b8 llint_entry + 119182
15  JavaScriptCore                	    0x7ff82ec8e3b8 llint_entry + 119182
16  JavaScriptCore                	    0x7ff82ec71027 vmEntryToJavaScript + 216
17  JavaScriptCore                	    0x7ff82f412161 JSC::Interpreter::executeCall(JSC::JSGlobalObject*, JSC::JSObject*, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 545
18  JavaScriptCore                	    0x7ff82f67a5cb JSC::profiledCall(JSC::JSGlobalObject*, JSC::ProfilingReason, JSC::JSValue, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&, WTF::NakedPtr<JSC::Exception>&) + 107
19  WebCore                       	    0x7ff8330efc0b WebCore::JSExecState::profiledCall(JSC::JSGlobalObject*, JSC::ProfilingReason, JSC::JSValue, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&, WTF::NakedPtr<JSC::Exception>&) + 107
20  WebCore                       	    0x7ff833107a61 WebCore::JSEventListener::handleEvent(WebCore::ScriptExecutionContext&, WebCore::Event&) + 849
21  WebCore                       	    0x7ff833464736 WebCore::EventTarget::innerInvokeEventListeners(WebCore::Event&, WTF::Vector<WTF::RefPtr<WebCore::RegisteredEventListener, WTF::RawPtrTraits<WebCore::RegisteredEventListener>, WTF::DefaultRefDerefTraits<WebCore::RegisteredEventListener> >, 1ul, WTF::CrashOnOverflow, 2ul, WTF::FastMalloc>, WebCore::EventTarget::EventInvokePhase) + 310
22  WebCore                       	    0x7ff833464336 WebCore::EventTarget::fireEventListeners(WebCore::Event&, WebCore::EventTarget::EventInvokePhase) + 342
23  WebCore                       	    0x7ff83345aee7 WebCore::dispatchEventInDOM(WebCore::Event&, WebCore::EventPath const&) + 215
24  WebCore                       	    0x7ff83345a221 WebCore::EventDispatcher::dispatchEvent(WebCore::Node&, WebCore::Event&) + 689
25  WebCore                       	    0x7ff83203c7e1 WebCore::Document::finishedParsing() + 497
26  WebCore                       	    0x7ff832036003 WebCore::HTMLDocumentParser::prepareToStopParsing() + 227
27  WebCore                       	    0x7ff8320aa09a WebCore::HTMLDocumentParser::resumeParsingAfterScriptExecution() + 90
28  WebCore                       	    0x7ff833761736 WebCore::HTMLDocumentParser::notifyFinished(WebCore::PendingScript&) + 54
29  WebCore                       	    0x7ff833498fc8 WebCore::PendingScript::notifyClientFinished() + 40
30  WebCore                       	    0x7ff8334800dc WebCore::LoadableScript::notifyClientFinished() + 284
31  WebCore                       	    0x7ff83347f8f1 WebCore::LoadableClassicScript::notifyFinished(WebCore::CachedResource&, WebCore::NetworkLoadMetrics const&) + 177
32  WebCore                       	    0x7ff8339ba2f7 WebCore::CachedResource::checkNotify(WebCore::NetworkLoadMetrics const&) + 167
33  WebCore                       	    0x7ff8339cf45b WebCore::CachedScript::finishLoading(WebCore::FragmentedSharedBuffer const*, WebCore::NetworkLoadMetrics const&) + 91
34  WebCore                       	    0x7ff83398b38b WebCore::SubresourceLoader::didFinishLoading(WebCore::NetworkLoadMetrics const&) + 699
35  WebCore                       	    0x7ff83436c2d4 WTF::Detail::CallableWrapper<-[WebCoreResourceHandleAsOperationQueueDelegate connectionDidFinishLoading:]::$_7, void>::call() + 388
36  JavaScriptCore                	    0x7ff82e916acf WTF::RunLoop::performWork() + 431
37  JavaScriptCore                	    0x7ff82e9173ba WTF::RunLoop::performWork(void*) + 26
38  CoreFoundation                	    0x7ff814d89bc8 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
39  CoreFoundation                	    0x7ff814d89b77 __CFRunLoopDoSource0 + 157
40  CoreFoundation                	    0x7ff814d89951 __CFRunLoopDoSources0 + 212
41  CoreFoundation                	    0x7ff814d885cb __CFRunLoopRun + 929
42  CoreFoundation                	    0x7ff814d87bb0 CFRunLoopRunSpecific + 560
43  HIToolbox                     	    0x7ff81e669bd6 RunCurrentEventLoopInMode + 292
44  HIToolbox                     	    0x7ff81e6699e6 ReceiveNextEventCommon + 679
45  HIToolbox                     	    0x7ff81e669723 _BlockUntilNextEventMatchingListInModeWithFilter + 70
46  AppKit                        	    0x7ff817eaab37 _DPSNextEvent + 909
47  AppKit                        	    0x7ff817ea99b8 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1219
48  libswt-pi-cocoa-4954r7.jnilib 	        0x26742798 Java_org_eclipse_swt_internal_cocoa_OS_objc_1msgSendSuper__Lorg_eclipse_swt_internal_cocoa_objc_1super_2JJJJZ + 168
49  ???                           	        0x19b6c081 ???
50  ???                           	        0x13f638c4 ???
51  libjvm.dylib                  	         0xd4bdc86 JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, JavaThread*) + 694
52  libjvm.dylib                  	         0xd521048 jni_invoke_static(JNIEnv_*, JavaValue*, _jobject*, JNICallType, _jmethodID*, JNI_ArgumentPusher*, JavaThread*) + 344
53  libjvm.dylib                  	         0xd5230f3 jni_CallStaticLongMethodV + 339
54  libswt-cocoa-4954r7.jnilib    	        0x29289534 callback + 1220
55  libswt-cocoa-4954r7.jnilib    	        0x2929e818 fn3_6 + 72
56  libswt-pi-cocoa-4954r7.jnilib 	        0x2673e1c4 Java_org_eclipse_swt_internal_cocoa_OS_objc_1msgSend__JJJJJZ + 84
57  ???                           	        0x19b6c470 ???
58  ???                           	        0x137c6ebc ???
59  ???                           	        0x11738862 ???
60  ???                           	        0x11738410 ???
61  ???                           	        0x1173867e ???
62  ???                           	        0x11738410 ???
63  ???                           	        0x11738410 ???
64  ???                           	        0x11738862 ???
65  ???                           	        0x11738410 ???
66  ???                           	        0x117382fc ???
67  ???                           	        0x117382fc ???
68  ???                           	        0x1173867e ???
69  ???                           	        0x1173867e ???
70  ???                           	        0x1173822c ???
71  ???                           	        0x1173822c ???
72  ???                           	        0x1173822c ???
73  ???                           	        0x1172fcc9 ???
74  libjvm.dylib                  	         0xd4bdc86 JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, JavaThread*) + 694
75  libjvm.dylib                  	         0xd8c4ac0 invoke(InstanceKlass*, methodHandle const&, Handle, bool, objArrayHandle, BasicType, objArrayHandle, bool, JavaThread*) + 2576
76  libjvm.dylib                  	         0xd8c405b Reflection::invoke_method(oopDesc*, Handle, objArrayHandle, JavaThread*) + 347
77  libjvm.dylib                  	         0xd56cc13 JVM_InvokeMethod + 819
78  ???                           	        0x1173c4da ???
79  ???                           	        0x1173822c ???
80  ???                           	        0x1173822c ???
81  ???                           	        0x1173867e ???
82  ???                           	        0x1173822c ???
83  ???                           	        0x11738410 ???
84  ???                           	        0x11738410 ???
85  ???                           	        0x1172fcc9 ???
86  libjvm.dylib                  	         0xd4bdc86 JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, JavaThread*) + 694
87  libjvm.dylib                  	         0xd5189b5 jni_invoke_nonstatic(JNIEnv_*, JavaValue*, _jobject*, JNICallType, _jmethodID*, JNI_ArgumentPusher*, JavaThread*) + 725
88  libjvm.dylib                  	         0xd51a6e0 jni_CallIntMethod + 416
89  eclipse_11700.so              	         0xa588fca startJavaJNI + 1946
90  eclipse_11700.so              	         0xa584eb0 _run + 6016
91  eclipse_11700.so              	         0xa58327a run + 426
92  eclipse                       	          0x704bed original_main + 1245
93  eclipse                       	          0x705521 main + 1665
94  dyld                          	    0x7ff81497e310 start + 2432
`

Stack trace from running eclipse from command line:

`!ENTRY org.eclipse.lsp4e 2 0 2022-11-01 13:24:44.463
!MESSAGE Could not get hover information due to timeout after 500 miliseconds
!STACK 0
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
	at org.eclipse.lsp4e.operations.hover.LSPTextHover.getHoverInfo(LSPTextHover.java:73)
	at org.eclipse.ui.internal.genericeditor.hover.CompositeTextHover.getHoverInfo2(CompositeTextHover.java:60)
	at org.eclipse.jface.text.TextViewerHoverManager$1.run(TextViewerHoverManager.java:155)
Uncaught exception received.
Error: Connection is closed.
    at se (/Users/scp/.p2/pool/plugins/org.eclipse.wildwebdeveloper_0.6.0.202206151321/node_modules/eslint-server/out/eslintServer.js:1:33782)
    at Object.sendNotification (/Users/scp/.p2/pool/plugins/org.eclipse.wildwebdeveloper_0.6.0.202206151321/node_modules/eslint-server/out/eslintServer.js:1:34678)
    at m.send (/Users/scp/.p2/pool/plugins/org.eclipse.wildwebdeveloper_0.6.0.202206151321/node_modules/eslint-server/out/eslintServer.js:1:133296)
    at m.error (/Users/scp/.p2/pool/plugins/org.eclipse.wildwebdeveloper_0.6.0.202206151321/node_modules/eslint-server/out/eslintServer.js:1:133096)
    at /Users/scp/.p2/pool/plugins/org.eclipse.wildwebdeveloper_0.6.0.202206151321/node_modules/eslint-server/out/eslintServer.js:1:35381
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Uncaught exception received.
Error: Connection is closed.
    at se (/Users/scp/.p2/pool/plugins/org.eclipse.wildwebdeveloper_0.6.0.202206151321/node_modules/eslint-server/out/eslintServer.js:1:33782)
    at Object.sendNotification (/Users/scp/.p2/pool/plugins/org.eclipse.wildwebdeveloper_0.6.0.202206151321/node_modules/eslint-server/out/eslintServer.js:1:34678)
    at Object.sendNotification (/Users/scp/.p2/pool/plugins/org.eclipse.wildwebdeveloper_0.6.0.202206151321/node_modules/eslint-server/out/eslintServer.js:1:140489)
    at process.exit (/Users/scp/.p2/pool/plugins/org.eclipse.wildwebdeveloper_0.6.0.202206151321/node_modules/eslint-server/out/eslintServer.js:1:174318)
    at Socket.<anonymous> (/Users/scp/.p2/pool/plugins/org.eclipse.wildwebdeveloper_0.6.0.202206151321/node_modules/eslint-server/out/eslintServer.js:1:155291)
    at Socket.emit (node:events:538:35)
    at Pipe.<anonymous> (node:net:687:12)`

**Comment by jonahgraham** [comment]
This looks like https://github.com/eclipse-platform/eclipse.platform.swt/issues/452 - can you have a look and see if that looks like the same issue to you?

**Comment by sgjohnston** [comment]
Yes, thank you, that looks like the same issue - at least the stack trace is very similar, and it makes sense. We can also reproduce it by using the internal web browser view.

Should this be linked to https://github.com/eclipse-platform/eclipse.platform.swt/issues/452 or is it OK just to close?

**Comment by jonahgraham** [comment]
I don't know if there is anymore linking to be done, it looks like this in SWT issue now:

![image](https://user-images.githubusercontent.com/679236/199268775-64683991-98da-4753-85d7-4bec4631419f.png)
