### ISSUE TITLE
Content Assist should request a new response from LS on typing when the previous response was incomplete

### ISSUE THREAD

**Issue by gerdleon** [eclipse/lsp4e#280]
The LS has the option to return an incomplete result on Content Assist. This is annotated in the response type `CompletionList` via `isInComplete=true`.

The LSP specification indicates that if the LS returns an incomplete `CompletionList` the client should request a new `CompletionList` when the user types.

**Comment by mickaelistria** [comment]
Isn't it already what's implemented?

**Comment by gerdleon** [comment]
I think you are right.

I was fooled by the behavior in the Xtext LSP implementation, where write requests cancel read-requests. 
We recently made an extension to Xtext that allows for dirty-state editing. So every typing in the source will cause a write request, which can cancel the reads requests.
