### ISSUE TITLE
Solargraph not working after eclipse-update from 2021-09 to 2021-12

### ISSUE THREAD

**Issue by AlBundy33** [eclipse/lsp4e#29]
I've created this issue because I cannot reopen #27 
@PyvesB checked my logfiles and it seems that the completion did not work because auf a change in lsp4e the deprecates rootUri in favor of workspacesFolders where workspaceFolders are send with a different uri-format.

in my case the URIs starting with with file:/Z:... instead of file:///Z:... which cannot be handled by solargraph.
It seems that rootUri was send with file:///Z:... and therefore it worked in eclipse 2021-09

@PyvesB added a really good esplanation to the issue I've created in his project: https://github.com/PyvesB/eclipse-solargraph/issues/17#issuecomment-991607202

**Comment by mickaelistria** [comment]
OK, that seems like an incorrect URI pattern according to the LSP and RFC-3986 spec. Patches welcome!

**Comment by PyvesB** [comment]
Worth noting that this issue also affects the Go language server in Eclipse 2021-12, as highlighted by https://github.com/briandealwis/gore/issues/1#issuecomment-1007144400.
