### ISSUE TITLE
Support Call-Hierarchy in LSP4E

### ISSUE THREAD

**Issue by gerdleon** [eclipse/lsp4e#291]
Since version 3.16 LSP supports Call-Hierarchy requests/responses (https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_prepareCallHierarchy).

AFAIK there is no support in LSP4E.
Is support planned in LSP4E? If not, is a contribution of this feature welcome? Any restrictions, concerns?

**Comment by mickaelistria** [comment]
I'm not aware of anyone who is planning to implement this, but yes a contribution would be welcome. Basically, all contributions that are about implementing the specifications are always welcome as per the formal project goal of LSP4E ;)

**Comment by rubenporras** [comment]
We are working on this and will create a PR soon to add the implementation to LSP4E.

**Comment by gerdleon** [comment]
Our contribution https://github.com/eclipse/lsp4e/commit/91d61ffe73be7183f33ff141c4822d3b4dfd1a95 provides the first basic Call-Hierarchy support.

**Comment by mickaelistria** [comment]
Let's close. Thanks for your contribution.
