### ISSUE TITLE
Feature request: support watch expressions with Debug Adapter Protocol

### ISSUE THREAD

**Issue by AndrewFerr** [eclipse/lsp4e#306]
When debugging a Node application, entering any expression in the Expressions view (even something trivial) fails with a value of "<error(s)_during_the_evaluation>" and a message of "(Watch expressions not supported".

It would be nice if the Expressions view could be supported, as being able to pinpoint variables to watch or test given expressions at runtime is a significant time-saver.

**Comment by mickaelistria** [comment]
Done. Please update to latest LSP4E snapshots to leverage this improvement.
