### ISSUE TITLE
Add preferences for auto inserting close characters. (or be smarter)

### ISSUE THREAD

**Issue by jcompagner** [eclipse/lsp4e#31]
I think this belongs to this project (and not WWD) but what is for the most time just annoying that if i type " that then i get also a second " or if  i type ' or { 

Many times i don't really want that i and have to delete it again (like if i make a if/else multi line and so on)

In the Java editor you have the auto close section in the preferences, but i can't find that for the editor that handles for example TS

Maybe we can also make it a bit more smarter because if you compare with the java editor if you do { then it will not right away insert a } but only later for example if i have this in the java editor:

if (true) statement;

then i can wrap statement easily in {} without java editor being to smart and adds one when i type { just after the if..
this is not possible in the typescript editor. and because of that i rather have it not do it at all.

**Comment by mickaelistria** [comment]
LSP doesn't tell anything about auto-closing pairs. This comes from TM4E project, please report it there.

**Comment by cdietrich** [comment]
theoretically i also could come from the OnTypeFormatting service, but i am not sure if the mentioned language server supports it

**Comment by jcompagner** [comment]
![image](https://user-images.githubusercontent.com/3274268/146172508-cc12257a-acc2-4f03-984a-d28721bd733d.png)

thx, you pointed me to the correct location when i search now more for it..
So it seems i can just disabled it.. so its kind of now making it a bit smarter...
I guess i can open a case for that at TM4E
