### ISSUE TITLE
TypeScript outline broken in latest snapshot

### ISSUE THREAD

**Issue by AndrewFerr** [eclipse/lsp4e#312]
With the (at the time of writing) latest snaphot of Wild Web Developer (1.0.1.202211171559) and its dependencies, the Outline view for TypeScript files is often broken, even for short files.

For example, a file with a single function will have an entry of "?" in the Outline.

For larger files, the Outline tends to look like this:
![image](https://user-images.githubusercontent.com/3271094/202967184-910dff15-3246-4216-839f-5124e77fae21.png)

Filing this under lsp4e since I assume it's the component that populates the Outline for TypeScript files.

(Also, if filing issues for snapshot releases is inappropriate, let me know & I'll refrain from filing any more in the future.)

**Comment by mickaelistria** [comment]
Can you please share a (simple if possible) file that reproduces that issue?

**Comment by AndrewFerr** [comment]
```typescript
function formatter(arg: string): string {
    return `>> ${arg} <<`;
}

console.log("Hello World");
for (const arg of process.argv.slice(2)) {
    console.log(formatter(arg));
}
```

This yields an Outline entry of `?`:
![image](https://user-images.githubusercontent.com/3271094/203070871-560e81f4-1f39-48e9-aa24-235fa5dd8db3.png)

Reverting to the latest stable release fixes it:
![image](https://user-images.githubusercontent.com/3271094/203071064-38062d50-7ff8-43f5-9850-433f4b83c60e.png)

**Comment by mickaelistria** [comment]
@AndrewFerr Can you please try latest snapshots? I cannot reproduce this issue with latest build.

**Comment by AndrewFerr** [comment]
Yes, the problem is gone after updating.  Thanks!  And apologies for my delayed response.
