### ISSUE TITLE
Every Outline view now has an extra "Sort Outline" toggle

### ISSUE THREAD

**Issue by nitind** [eclipse/lsp4e#35]
org.eclipse.lsp4e 0.13.8.202111241523 bundle in the Enterprise Java and Web 2021-12 Release package.

Every editor I open is getting an additional "Sort Outline" toggle in its Outline view, even ones that already have their own sort option, and editors that don't even have outlines. From what I can tell, it's been added to the View itself, not just to the ContentOutlinePages' site's actionbars where it makes sense.

<img width="310" alt="Screen Shot 2022-01-15 at 12 43 36 AM" src="https://user-images.githubusercontent.com/2684153/149610622-8802dd5e-1485-490d-8d12-6ed5cf1ec4aa.png">

Additionally, the label does not need to include the word, "Outline", and it does not appear to be properly externalized.

**Comment by mickaelistria** [comment]
@vrubezhny Please investigate; the contribution needs a visibleWhen element that would only apply if the outline view comes from LSP4E.
