### ISSUE TITLE
lsp for php 

### ISSUE THREAD

**Issue by rulon** [eclipse/lsp4e#350]
I did try link from you readme section "Examples"

Examples of integration contain:
...
[language-servers-for-eclipse](https://github.com/eclipselabs/language-servers-for-eclipse) Binds various language servers to the Eclipse IDE.

but that project returned 404 from update link:
Update site: https://dl.bintray.com/mniewrzal/language-servers-for-eclipse/snapshot/

Is there an any example implementation of php8 language servers and connection from lsp4e?

**Comment by mickaelistria** [comment]
Sorry, I don't know and this particular implementation is beyond the scope of LSP4E project. Have you opened as issue to ask it to @mniewrzal on https://github.com/eclipselabs/language-servers-for-eclipse/issues ?
