### ISSUE TITLE
561372 - DocumentLinkDetector timeout too long 

### ISSUE THREAD

**Issue by erik-brangs** [eclipse/lsp4e#36]
The associated bug [561372](https://bugs.eclipse.org/bugs/show_bug.cgi?id=561372) from the Eclipse bug tracker is still happening in Eclipse IDE 2021-12.

Please note that this is distinct from [573312](https://bugs.eclipse.org/bugs/show_bug.cgi?id=573312) because I don't have any Spring tooling installed and still have problems with the DocumentLinkDetector timeout.

**Comment by erik-brangs** [comment]
Please note that I could not link the Eclipse bug to this issue. I don't seem to have the required permissions in the Eclipse bug tracker.

**Comment by sebthom** [comment]
Are you still faced with this issue using the latest LSP4E release? If so, please provide a new stacktrace.

**Comment by erik-brangs** [comment]
I haven't seen this problem for a while.
