### ISSUE TITLE
memory leak in ConnectDocumentToLanguageServerSetupParticipant

### ISSUE THREAD

**Issue by martinlippert** [eclipse/lsp4e#377]
While analyzing a heap dump of an IDE instance running for some time, I came across the `ConnectDocumentToLanguageServerSetupParticipant` and it looks like the Job objects are not removed from `SUBMITTED_JOBS` all the time.

It looks like the `run` method should remove the job objects from the map in all the cases, not only after getting the language servers.

**Comment by ahmedneilhussain** [comment]
You're right, that's my bad. I'll submit a patch.

**Comment by martinlippert** [comment]
Fixed via https://github.com/eclipse/lsp4e/pull/380
