### ISSUE TITLE
 Keyboard shortcut CTRL+SHIFT+T clash in default binding between Language Server and JDT

### ISSUE THREAD

**Issue by de-jcup** [eclipse/lsp4e#378]
## Situation
I upgraded my eclipse IDE to:
- Version: 2022-12 (4.26.0)
- Build id: 20221201-1913
- OS : Linux

_(I did not have the problem with 2022-09)_

Problem: I am using `CTRL`+`SHIFT`+`T`  more than 17 years now to show the "Open type" dialog in eclipse when writing Java code. But now there is a name clash : The language server parts have introduced same short cut for "Go to Symbol in Workspace". Because of this situation there is always a selection inside the window necessary which variant shall be used when pressing the shortcut inside a Java editor - very annoying/slowing down workflow.

I originally made an issue at JDT - see https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/394 but it is more something that comes from lsp4e, so it should be addressed here.

### Details
![image](https://user-images.githubusercontent.com/11644753/212825047-d308cb3f-c373-409f-8ce4-481d6498428c.png)

## Wanted
As a user I do not want to have always a selection prompting/a clash between those two parts

## Suggestion
If the keyboard binding for lsp4e would not be for the complete window but only inside the generic editor this would be more suitable.
I did change my own preferences in following way and it works well for me.

![image](https://user-images.githubusercontent.com/11644753/213223349-093e313b-b426-4037-ac25-bb06ee7e3433.png)

It would be nice if the initial setup from lsp4e would produce no binding problems.

**Comment by mickaelistria** [comment]
I'm closing this in LSP4E, it's more properly actionable on JDT end: https://github.com/eclipse-platform/eclipse.platform.ui/issues/513#issuecomment-1468778600
