### ISSUE TITLE
Provide context variable for resource to be opened in contentTypeMapping -> enabledWhen - > with statement

### ISSUE THREAD

**Issue by ghentschke** [eclipse/lsp4e#393]
Hi All, 
we are developing an LSP based C/C++ editor using the generic text editor and LSP4E. Now I run into the problem that there are several editors for a C/C++ content-type (e.g. `org.eclipse.cdt.core.cSource`) in Eclipse and LSP4E uses the content-type to run a certain language server. 
In our case, the clangd language server shall be used only for new C/C++ Projects which are associated with the new LSP C/C++ editor. **Files in old projects shall be opened by the CDT C-Editor without starting a language server when a  C-file is opened**.
Therefore I'am providing a `PropertyTester` which checks the file to be opened. This test is used in the `enabledWhen` statement for the `contentTypeMapping` in the `org.eclipse.lsp4e.languageServer` extension point.  This ensures that the language server is only enabled, when a certain project nature has been set:

![image](https://user-images.githubusercontent.com/123444711/214239920-90363cb2-c271-46c8-8cb1-230c97acf807.png)
with new `openResource` variable:
![image](https://user-images.githubusercontent.com/123444711/214242529-4a9c5c66-37f9-47c6-9b84-39043d4169a3.png)

LSP4E has the information which resource shall be opened. It would be fantastic if this object is forwarded to the context in the org.eclipse.lsp4e.enablement.EnablementTester as a variable to be used in a `PropertyTester` class. I added a variable named `openResource` to the `evaluate` method in the `EnablementTester` to test my approach:
![image](https://user-images.githubusercontent.com/123444711/214243072-4674975e-ae6c-44f2-aec6-d22578669ee9.png)

The `openResource` object can be a `IFile`, `IEditorInput` or `IDocument` which can be checked in the enabledWhen test.  

What do you think?

**Comment by mickaelistria** [comment]
Adding something like `currentDocument` to the evaluation context wouldn't hurt and can indeed be helpful. Please consider contributing this.

**Comment by ghentschke** [comment]
@mickaelistria can you please review my last commit. I added a default variable to the evaluation context

**Comment by mickaelistria** [comment]
For consistency, the default variable should be a document. The "resource" or "editor" can be extra additional variables for the context, but document is the central object of LSP4E.

**Comment by mickaelistria** [comment]
I think this was fixed with #400
