### ISSUE TITLE
Type hierarchy support

### ISSUE THREAD

**Issue by ghentschke** [eclipse/lsp4e#403]
Hi, 
I haven't found support for type hierarchy. Does anybody working on this already?

**Comment by mickaelistria** [comment]
No-one is working on it yet as far as I know. If you're willing to contribute it, that would be very welcome!

**Comment by mickaelistria** [comment]
WIP at #580 ; I'm currently targeting mostly/only JDT-LS and didn't try it against other LS (and don't plan to). So if you're willing to try the draft PR, and report how good/bad it is and participate in its finalization, it would be welcome.

**Comment by ghentschke** [comment]
Good news! Yes I'll try this out

**Comment by rubenporras** [comment]
Great news to see this missing feature being worked on!
