### ISSUE TITLE
Remove option to log protocol messages to console?

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lsp4e#424]
In #419, it's hightlighted that logging LSP messages to the console can be a source of problems. I think we should just remove this functionality; and that looking at log files in an (Eclipse or external) editor or console is more efficient.
Is there any contributor relying on this feature?

**Comment by martinlippert** [comment]
No objections from my side, even though I think that logging those messages to the console is quite handy and should probably only be enabled and used while investigating issues - and not during regular use.

**Comment by mickaelistria** [comment]
Discussion at https://github.com/eclipse/lsp4e/discussions/419#discussioncomment-4831005 seems to show that many committers want to keep the log to console. So let's keep it.
