### ISSUE TITLE
Invalid argument exception for CompletableFuture -> thenAcceptAsync

### ISSUE THREAD

**Issue by ghentschke** [eclipse/lsp4e#438]
Hi,
I get invalid argument exceptions in `org.eclipse.lsp4e.operations.format.LSPFormatHandler.execute(ExecutionEvent)` and `org.eclipse.lsp4e.operations.color.ColorInformationMining.UpdateColorWithDialog.accept(MouseEvent) `because Java says the second argument is not an executor:

![image](https://user-images.githubusercontent.com/123444711/217477092-cb7b357a-1803-4d1f-84ab-d36bd503395f.png)

In both cases the second argument in the `thenAcceptAsync` call is an instance of Display. As far as I've seen Display does not implement Executor.

Can anybody help me out why this does not work on my machine? I am using Java 17

**Comment by mickaelistria** [comment]
Are you using a recent enough Eclipse Platform in as target-platform? Display has started implementing Executor not that long ago, so if you target an older version, then this error can show.
Note that LSP4E MANIFEST.MF should be modified to properly set the minimal version of SWT it depends on being the one that introduced `Dispaly implements Executor`, so you'd see an error on the MANiFEST with a more explicit message and thus easier to figure out what remediation would be.

**Comment by ghentschke** [comment]
Thank you. I am not on the latest platform!
