### ISSUE TITLE
Spurious content assist popup when save/copy in recent Eclipse

### ISSUE THREAD

**Issue by ahmedneilhussain** [eclipse/lsp4e#443]
Confirmed in 2022-12, not present in 2020-x. I think very recent.

Use e.g. corrosion plugin and move to a point of whitespace in a rust file, e.g. between two identifiers. Assume the file is saved. Press cmd-S to save the file (on MacOS). The content assist pops up. Also triggered if you press cmd-C without anything selected, and also some unbound keys.

I've tracked it down to `org.eclipse.jface.text.contentassist.ContentAssistant.AutoAssistListener.keyPressed(KeyEvent)` in the platform. It looks like it is treating the character cmd-S as though I had just typed s for the purposes of triggering content assist. The logic in that method looks to see if `alt` is present in the flags, but not `cmd`. I guess on Windows and Linux you don't see the problem because eg ^S will be passed around as a code point < 32.

It seems to be quite general - any hotkey combination involving an alphabetic character that doesn't cause a command to be run seems to trigger it. So if you cmd-S on an unsaved file or cmd-C with some text highlighted then you don't get the popup, presumably because the command framework marks the event as having been processed and not requiring further propagation.

Pretty sure it's a platform thing rather than an LSP4e thing - we use an old private fork of LSP4e: it reproduces both with that and with modern LSP4e in 2022-12 but not in older versions of Eclipse. I guess if `ContentAssistant` is the culprit then it affects any use of the `jface` editor, not just LSP4e.

Has anyone else run into it? Surprised nobody else has reported it but if it's only very recent eclipse, and only on MacOS, then that might explain it.

**Comment by mickaelistria** [comment]
> Pretty sure it's a platform thing rather than an LSP4e thing 

Then can you please report it to Platform? I suspect you'll need to use the generic editor to reproduce it.

**Comment by ahmedneilhussain** [comment]
Thanks, I've submitted https://github.com/eclipse-platform/eclipse.platform.text/pull/150 as a proposed fix.
