### ISSUE TITLE
LSP4E p2 update site points to 0.13.8 version instead of 0.20.1. Why???

### ISSUE THREAD

**Issue by BoykoAlex** [eclipse/lsp4e#45]
I've used the p2 update site stated on the LSP4E eclipse page here: https://projects.eclipse.org/projects/technology.lsp4e/downloads
In other words p2: http://download.eclipse.org/lsp4e/releases/latest/

If i attempt to install latest lsp4e from that update site i get:
![Screen Shot 2022-01-14 at 16 04 34](https://user-images.githubusercontent.com/6433390/149585380-05258215-e845-4486-ab04-afef8a4a9dc9.png)

Note the version: 0.13.8.

Why is it not the 0.20.1 which stated to be the latest here: https://projects.eclipse.org/projects/technology.lsp4e

**Comment by mickaelistria** [comment]
LSP4E, like Eclipse Platform and many others, does use semantic versioning. So the "marketing"version (0.20.1) can contain artifacts with different versions, according to the type of changes that took place in the release.
