### ISSUE TITLE
Semantic highlighting seems to remove syntax highlighting for JavaScript files

### ISSUE THREAD

**Issue by martinlippert** [eclipse/lsp4e#537]
As reported here: https://github.com/spring-projects/sts4/issues/702#issuecomment-1457036483 - the semantic highlighting of LSP4E seems to cause the regular syntax highlighting for JavaScript files to (more or less) go away. This doesn't look right to me, but I don't have deep insights into this area. WDYT?

**Comment by mickaelistria** [comment]
I think it's related to #517 and/or #522

**Comment by rubenporras** [comment]
Yes, @martinlippert , could you retry with the latest snapshot?

**Comment by martinlippert** [comment]
@rubenporras Works perfectly now, thanks!!! So closing this one here.

**Comment by rubenporras** [comment]
I am happy that it fixed the issue for you. Just in case you are interested, I think your LS supports semantic highlight and is sending token information back, but you have not configured a way to map those tokens to a style. If that is so it is a pity that you do not use the information to improve the presentation.

**Comment by martinlippert** [comment]
@rubenporras Actually, we use the WWD support for JavaScript here, so looks like the token <-> style mapping should be included there, right?

**Comment by rubenporras** [comment]
it looks like either TM4E is not properly configured or the server sends tokens which have no style set on the client side. Maybe you should check org.eclipse.lsp4e.operations.semanticTokens.TokenTypeMapper.apply(String) to understand which one it is (that is, when it returns null).
