### ISSUE TITLE
"Computing Proposals" stays forever in AsyncCompletionPopup

### ISSUE THREAD

**Issue by rubenporras** [eclipse/lsp4e#550]
Hi,

I experience a very bad behavior on while typing on places where the server does not return any completion proposal, see the following screenshot:

![image](https://user-images.githubusercontent.com/43636626/225046160-ccd9a2a0-d540-4ec7-b184-ce8224132dca.png)

What happens is while typing the name of the element definition (which has no possible proposal), the popup is displayed and stays **forever** until I type further. I think that that it pops up is already bad behaviour, since the user did not asked for content assist, but that it stays forever is also not nice.

Also the message 0% and "1 completed, 0 pending" do not make much sense.

I have checked org.eclipse.lsp4e.operations.completion.LSContentAssistProcessor.computeCompletionProposals(ITextViewer, int) and it returns an empty array, so I would not expect the problem to be there. Would it be a bug in the platform?

Any help would be much appreciated, since I am lost finding the problem.

Thanks

**Comment by mickaelistria** [comment]
It would be great if you can reproduce it with the MockLanguageServer that's used inside tests.

**Comment by rubenporras** [comment]
Proposal to fix it in https://github.com/eclipse-platform/eclipse.platform.text/pull/183

**Comment by rubenporras** [comment]
Fixed in eclipse platform text.
