### ISSUE TITLE
Add hyperlinked documents to origin LS

### ISSUE THREAD

**Issue by ghentschke** [eclipse/lsp4e#555]
When opening a linked external file/document, this file should be connected to the language server of the origin document.

This ensures that convenient language server(s) will be used for the linked file. This becomes important when using one LS per project in the Eclipse workspace. 

Background: Applicable when using a non singleton language server which does not support multi projects / workspace folder capability.

In the current implementation a new wrapper/server will be started for each, via hyperlink opened, external file. This lead to the following problems:
- The LS cannot find a compilation database for external files
- Excessive usage of LS when many external files are opened.

I can provide a PR for this issue.

**Comment by mickaelistria** [comment]
> non singleton language server which does not support multi projects / workspace folder capability.

So how do we know such language server is able to process random files? I'm not sure we can reliably generalize such decision to use the same instance for opened files; this is deeply specific to 1 LS or the other.

**Comment by ghentschke** [comment]
I don't think it's for random files. The adding is related only to external files with the same content type as the LS supports.  The use case is for C/C++ very common: to include standard library header files form a C/C++ source or header. 

The problem is how to tell the LS which compilation database it should use for external source code files. The usage depends on the origin file. The compiler settings used to compile the source file should be used for the external file as well. That's why this change is so important.

**Comment by ghentschke** [comment]
> Most language server fix that by either being singleton or enabling workspace folders support

I'll check that. Thank you.

One more question. What is the desired behavior for hyperlinked files of LSP4E when the LS is singleton and the LS does not support workspace folders regarding LS/wrapper? In the current implementation a new LS/wrapper will be started for each opened file.

**Comment by mickaelistria** [comment]
> What is the desired behavior for hyperlinked files of LSP4E when the LS is singleton and the LS does not support workspace folders regarding LS/wrapper?

Initially, LSP4E was not using workspace folders, and the expected behavior was that only one instance of a wrapper/or a LanguageServer gets started. So under this expectation, the behavior you describe seems more like a bug.

**Comment by ghentschke** [comment]
@mickaelistria Sorry, I forget the NOT: 
> What is the desired behavior for hyperlinked files of LSP4E when the LS is NOT a singleton and the LS does not support workspace folders regarding LS/wrapper? 

Currently a new LS will be started for each external file when the server is NOT a singleton. As a user I cannot change this behavior.

>> This case seems relatively specific to your particular LS integration; I suspect it would better fit in the plugin that provides the LS integration than into LSP4E commons. 

IMO is the plugin that provides the LS integration equal to LPS4E. As a language server provider plugin using the `languageServer` extension point I cannot control how an when a new LS/wrapper will be spawned. When a language server has been tagged NOT as a singleton, I cannot decide when to start a new server.  The logic is in the `canOperate` methods in the wrapper.  

A solution would be, to led the LS provider provide the logic for spawning new LS in case of singleton = false. This would override the logic in canOperate.

The discussion in [A way for a LS to declare its project association cardinality](https://github.com/Microsoft/language-server-protocol/issues/674) points to the same root problem: How to decide whether to 
> spawn a new LS or to re use an existing one for a given file
