### ISSUE TITLE
Incorrect tooltip generated when the server returns an empty string for documentation (Bug 567292)

### ISSUE THREAD

**Issue by jeffmaury** [eclipse/lsp4e#6]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=567292

![lsp4e](https://user-images.githubusercontent.com/695993/142247238-7deb19f1-2797-4ea9-92ce-7a61e54c747f.png)

**Comment by akurtakov** [comment]
Can you please provide a test case verifying this bug?
