### ISSUE TITLE
Outline view should provide more visual separation displaying symbols gathered from properties files

### ISSUE THREAD

**Issue by scottkurz** [eclipse/lsp4e#615]
## PROBLEM

Using Eclipse 4.27 with Quarkus Tools (using LSP4MP 0.6)  I see this for application.properties in the Outline view 

![image](https://user-images.githubusercontent.com/4081634/233495061-ddadc023-2d50-412d-af16-2338a9909625.png)

Note how the key and value are collapsed together without a space.

On the other hand, looking at a Java file in Eclipse, we see  `<element name> : <type>` with the space and colon.

![image](https://user-images.githubusercontent.com/4081634/233495217-3a5c04af-aa09-49b1-a2c3-3020002e28e5.png)

## SUGGESTION

I think simply adding a space, combined with the different font, would be enough of a separation (we don't need the ':' IMHO).

## OTHER INFO

Note the [comment](https://github.com/eclipse/lsp4mp/issues/386#issuecomment-1516851206) showing the JSON-RPC payload returned by LSP4MP in a case similar to my screenshot.   (I first opened the issue against LSP4MP before getting directed here).

**Comment by scottkurz** [comment]
> I confirm what @angelozerr says in the other issue, it's definitely a client-side issue, more specifically in SymbolsLabelProvider . Would you be interested in submitting a PR that adds the necessary space?

Yes, I'd be interested.  Not sure exactly when I'll get to it but thanks for the starting point suggestion.

**Comment by ghentschke** [comment]
I stumbled across the same issue. I can provide a PR as well.
