### ISSUE TITLE
Override markerType in IMarkerAttributeComputer

### ISSUE THREAD

**Issue by ChristophKaser** [eclipse/lsp4e#645]
I am trying to have some "special" diagnostics appear different to the "default" diagnostics in the Editor, e.g. to indicate diagnostics differently depending on the source. The easiest way to do that seems to be to specify a different markerType and configure the annotationType per markerType (or maybe I got lost in the Marker vs Annotation distinction?).

Unfortunately, while I can configure marker attributes per diagnostic in IMarkerAttributeComputer, there is no way to override the markerType.

I suggest adding a constant IMarkerAttributeComputer.MARKER_TYPE that can be used in addMarkerAttributesForDiagnostic to set the markerType by setting it in attributes:

```java
public void addMarkerAttributesForDiagnostic(Diagnostic diagnostic, IDocument document, IResource resource, Map<String, Object> attributes) {
  attributes.put(IMarkerAttributeComputer.MARKER_TYPE , "de.dummy.marker_type");
}
```

Alternatively, a new method in IMarkerAttributeComputer like 
`String getMarkerTypeForDiagnost(Diagnostic diagnostic, IDocument document, IResource resource)` 
(with a default implementation returning null) might be a clearer design.

The returned marker type would need to be used in `LSPDiagnosticsToMarkers.updateMarkers`, which would require to determine `toDeleteMarkers`  without looking for a specific marker type. I don't think that is a problem, however, since findMarkers seems to accept null as type, and the LANGUAGE_SERVER_ID attribute of the marker is checked anyway.

What do you think about this proposal? Am I missing something?
If you think that this proposal makes sense, I can try to provide a PR.

**Comment by rubenporras** [comment]
Hi @ChristophKaser ,

you can configure it using the makerType attribute in the extension
         point="org.eclipse.lsp4e.languageServer", but that would only work for you if you have different servers for the different source types. Is that enough for you or are you using a singleton server?

@mickaelistria , if the solution can be replicated, then fair enough, we can go other ways, but removing and creating the marker again will have a performance impact (as far as I remember it will lock the workspace during the operation). Also the user might see flickering if he has the markers view open. So it would not be the same. I think updating the markers attributes in a listener will have a similar problem. Since the current API is very small and well defined, and does not cause any harm, I would rather keep it, or am I mistaken about the implications.

**Comment by ChristophKaser** [comment]
Hi @rubenporras 

> you can configure it using the makerType attribute in the extension
point="org.eclipse.lsp4e.languageServer", but that would only work for you if you have different servers for the different source types. Is that enough for you or are you using a singleton server?

Unfortunately, I have a singleton server that provides a wide range of diagnostics, so that solution does not really work for me.

Hi @mickaelistria ,

> Would it be possible for you to add a WorkspaceListener on IMarkers, and check that the newly created markers are problems with a Diagnostic and a certain LS defined in attribute, and in such case, just remove and recreate them with the proper type?

Unfortunately, this does have severe performance implications, since it causes even unchanged markers to be recreated every time a diagnostic was sent. Furthermore, when the last diagnostic is removed by the server, I do not get a change event (because the corresponding marker was removed by my ResourceChangeListener and recreated with a different type, so LSPDiagnosticsToMarkers does not find it) and therefore I have no way of removing my custom marker for this diagnostic.

What I might try to do instead is simply "fork" my own version of LSPDiagnosticsToMarkers and set it as diagnosticsConsumer in the language client. This would however mean duplicating some code, but it might be the easiest solution for now.

**Comment by mickaelistria** [comment]
> Unfortunately, this does have severe performance implications, since it causes even unchanged markers to be recreated every time a diagnostic was sent

Indeed, there are preformance implications, but I don't think they would qualify as "severe" in practice.

> when the last diagnostic is removed by the server, I do not get a change event

LSP4E should automatically remove the marker for such diagnostic, as long as this marker type is a child of `org.eclipse.lsp4e.diagnostic`.

**Comment by ChristophKaser** [comment]
>Indeed, there are preformance implications, but I don't think they would qualify as "severe" in practice.
In my case, they caused any edit to freeze the UI for some seconds while it was waiting to lock the workspace due to a parallel running refresh operation. This might have been caused by the way I implemented my prototype however.

>LSP4E should automatically remove the marker for such diagnostic, as long as this marker type is a child of org.eclipse.lsp4e.diagnostic.
I don't think it does, since LSPDiagnosticsToMarkers looks for markers to delete without considering subtypes.

But I have explored the custom diagnostics consumer further, and I think this way offers the most flexibility for my use case: It allows me to skip markers altogether and only use annotations, which fits the way this language server works better.

**Comment by mickaelistria** [comment]
> since LSPDiagnosticsToMarkers looks for markers to delete without considering subtypes

OK, I think that can be interpreted as a bug. A PR to look for subtypes would most likely be welcome.

**Comment by rubenporras** [comment]
I think that the solution involving a job is a bit clumsy but the requirement of having another icon depending on the source is also quite special, so if you and Mickael agree that PR #649 is enough, then I am happy as well.

**Comment by ChristophKaser** [comment]
It does feel a bit clumsy, but I get that this requirement is unusual and that you don't want to increase the API surface for such a special case.
Thank you both for your answers!
