### ISSUE TITLE
Add toggle to type hierarchy to switch between Subtypes/Supertypes

### ISSUE THREAD

**Issue by ddscharfe** [eclipse/lsp4e#674]
The type hierarchy currently only shows subtypes. It would be nice to have a toggle to switch between showing subtypes/supertypes.

See also issue #403 and PR #580 .

I can provide a PR for this, unless there is already someone else working on this.

**Comment by mickaelistria** [comment]
AFAIK, no-one is currentlly planning to work on this, and there is no doubt this feature would be valuable. So feel free to submit a PR ;)
