### ISSUE TITLE
Display diagnostic's codeDescription

### ISSUE THREAD

**Issue by amurashkin17** [eclipse/lsp4e#682]
In bash language server 4.1.0 diagnostics, "codeDescription.href" attribute contains URL to a shellcheck webpage describing the message. It would be nice to be able to go to that webpage (for example, by clicking or via a key shortcut)

```
{
    "message":"$/${} is unnecessary on arithmetic variables.",
    "severity":4,
    "code":"SC2004",
    "source":"shellcheck",
    "range":{"start":{"line":37,"character":11},"end":{"line":37,"character":17}},
    "codeDescription":{"href":"https://www.shellcheck.net/wiki/SC2004"}
},
```

**Comment by mickaelistria** [comment]
> Duplicate of https://github.com/eclipse/lsp4e/issues/185?

Yes ;)
