### ISSUE TITLE
Show diagnostic code as `[code]` suffix in the UI message

### ISSUE THREAD

**Issue by amurashkin17** [eclipse/lsp4e#686]
Please add SCxxx prefix to shellcheck messages in Eclipse.

In ShellWax 1.2.2.20221209-1429, shellcheck error messages do not include SCxxx code, for example

_read without -r will mangle backslashes_
**echo "$*" | while IFS= read line; do**

In ShellWax 1.2.1.20220825-0947, SCxxx code is there

_SC2162: read without -r will mangle backslashes_
**echo "$*" | while IFS= read line; do**

In bash language server 4.1.0 diagnostics, "message" attribute does not have SCxxx prefix, for example
```
{
    "message":"$/${} is unnecessary on arithmetic variables.",
    "severity":4,
    "code":"SC2004",
    "source":"shellcheck",
    "range":{"start":{"line":37,"character":11},"end":{"line":37,"character":17}},
    "codeDescription":{"href":"https://www.shellcheck.net/wiki/SC2004"}
},
```

In bash language server 3.1.0 diagnostics, "message" attribute has SCxxx prefix, for example

```
{
    "message":"SC2086: Double quote to prevent globbing and word splitting.",
    "severity":3,
    "code":2086,
    "source":"shellcheck",
    "range":{"start":{"line":35,"character":13},
    "end":{"line":35,"character":17}}
}
```

**Comment by amurashkin17** [comment]
In [LSPDiagnosticsToMarkers.java accept()](https://github.com/eclipse/lsp4e/blob/dd11ea70e2e3cfed2037b6fd7fd41030722f08ca/org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/diagnostics/LSPDiagnosticsToMarkers.java#L87) there are two cases

```java
String uri = diagnostics.getUri();
IResource resource = LSPEclipseUtils.findResourceFor(uri);
if (resource != null && resource.isAccessible()) {
    updateMarkers(diagnostics, resource);
} else {
    LSPEclipseUtils.findOpenEditorsFor(LSPEclipseUtils.toUri(uri)).stream()
    ...
    .forEach(sourceViewer -> updateEditorAnnotations(sourceViewer, diagnostics));
}
```

### Easily found resource - updateMarkers() case

In the case of updateMarkers(), [computeMarkerAttributes()](https://github.com/eclipse/lsp4e/blob/dd11ea70e2e3cfed2037b6fd7fd41030722f08ca/org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/diagnostics/LSPDiagnosticsToMarkers.java#L223) is called. It has line [239](https://github.com/eclipse/lsp4e/blob/dd11ea70e2e3cfed2037b6fd7fd41030722f08ca/org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/diagnostics/LSPDiagnosticsToMarkers.java#L239)

```java
attributes.put(IMarker.MESSAGE, diagnostic.getMessage());
```
That seems easy place to add the code suffix.

### Iterating through resources - updateEditorAnnotations() case

In the case of [updateEditorAnnotations()](https://github.com/eclipse/lsp4e/blob/dd11ea70e2e3cfed2037b6fd7fd41030722f08ca/org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/diagnostics/LSPDiagnosticsToMarkers.java#LL108C15-L108C38), there are lines [121-130](https://github.com/eclipse/lsp4e/blob/dd11ea70e2e3cfed2037b6fd7fd41030722f08ca/org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/diagnostics/LSPDiagnosticsToMarkers.java#L121)

```java
IAnnotationModel annotationModel = sourceViewer.getAnnotationModel();
...
diagnostics.getDiagnostics().forEach(diagnostic -> {
...
    int startOffset = LSPEclipseUtils.toOffset(diagnostic.getRange().getStart(), sourceViewer.getDocument());
    int endOffset = LSPEclipseUtils.toOffset(diagnostic.getRange().getEnd(), sourceViewer.getDocument());
    toAdd.put(new DiagnosticAnnotation(diagnostic), new Position(startOffset, endOffset - startOffset));
...
});
annotationModelExtension.replaceAnnotations(toRemove.toArray(new Annotation[toRemove.size()]), toAdd);
```

Do we care about updateEditorAnnotations() case? It calls neither updateMarkers(), nor  computeMarkerAttributes(). But computeMarkerAttributes() deals with many other marker attributes besides "message". For example, it sets "severity".

**Comment by mickaelistria** [comment]
> Do we care about updateEditorAnnotations() case? 

Not much. It would be totally fine to have a patch only for the marker case at the moment, and to -maybe- add the car of editor annotations later if someone needs it.

**Comment by sebthom** [comment]
Resolved via https://github.com/eclipse/lsp4e/pull/1065
