### ISSUE TITLE
ConnectDocumentToLanguageServerSetupParticipant 100% CPU usage

### ISSUE THREAD

**Issue by jukzi** [eclipse/lsp4e#696]
I had Eclipse.exe open for several days and somewhen it drained more and more CPU. finally it eat all my CPU
Sampling showed all CPU time was eaten by:
`org.eclipse.lsp4e.ConnectDocumentToLanguageServerSetupParticipant.lambda$0 ()`
in multiple ForkJoinPool Threads in parrallel
![image](https://github.com/eclipse/lsp4e/assets/51790620/ddb93e26-6221-46bf-b105-e037b53e3848)

**Comment by jukzi** [comment]
link to relevant code:
https://github.com/eclipse/lsp4e/blame/80d2076d1d5ed8cbcf6c73d8d53082a5fe398331/org.eclipse.lsp4e/src/org/eclipse/lsp4e/ConnectDocumentToLanguageServerSetupParticipant.java#L58

**Comment by sebthom** [comment]
Are you still seeing this issue with the current release?

**Comment by jukzi** [comment]
> I had Eclipse.exe open for several days

i did not have this condition in the past weeks

**Comment by sebthom** [comment]
Thanks for your reponse. I am closing the ticket for now. If the issue reappears please reopen.
