### ISSUE TITLE
Fix SymbolsModel.getParent for DocumentSymbolWithURI and DocumentSymbol

### ISSUE THREAD

**Issue by rubenporras** [eclipse/lsp4e#724]
With commit 7f4483a720a25ffa2f3b0f8a69c5e8ec3acd1cc7 the parts in SymbolsModel.getParent for DocumentSymbolWithURI and DocumentSymbol have been removed because they always returned just null.

We should implement properly those branches, as they are necessary for some things like expand or other operations on the viewer to work properly

**Comment by mickaelistria** [comment]
Isn't it fixed by #723? if yes, please close it.

**Comment by mickaelistria** [comment]
No news here, let's assume it's fixed. Please reopen if not.
