### ISSUE TITLE
Restart LS via API command

### ISSUE THREAD

**Issue by ghentschke** [eclipse/lsp4e#726]
As a  user I want to modify the language server command properties. To apply the changes, the running language server has to be restarted. 

Is there already a way to restart the LS after command properties, who are set via `org.eclipse.lsp4e.server.ProcessStreamConnectionProvider.setCommands(List<String>)` has been modified?

**Comment by mickaelistria** [comment]
I don't think the current API are sufficient to achieve that. One would need to add some `stop` method to `ProcessStreamConnectionProvider`, running `process.destroyForcibly()`. Adding such a method would be welcome.
Then in LanguageServerWrapper, we could add a method `stop(alsoForceStreamProviderStop)` which would invoke the new method.

**Comment by ghentschke** [comment]
> One would need to add some stop method to ProcessStreamConnectionProvider, running process.destroyForcibly()

Why is the actual stop() method in `ProcessStreamConnectionProvider` calling `process.destroy()` not sufficient?

**Comment by mickaelistria** [comment]
Yes, that would be sufficient. Then I don't get it: what extra API do you need?

**Comment by ghentschke** [comment]
Sorry. You are right. Now I figured out a solution without any API changes needed. This is what does it for me:
```java
LanguageServiceAccessor.getStartedWrappers(null, null, true).stream()
	.filter(w -> "org.eclipse.cdt.lsp.server".equals(w.serverDefinition.id)) //$NON-NLS-1$
	.forEach(w -> w.stop());
```
So I am closing this issue. @mickaelistria Thank you for the support!
