### ISSUE TITLE
Completion "hangs" with no response 

### ISSUE THREAD

**Issue by vrubezhny** [eclipse/lsp4e#743]
In some cases Completion hardly "hangs" without a response from server logged, like:
```
[2023-07-20T15:04:27.107621992+02:00] LSP4E_TO_LANGUAGE_SERVER org.eclipse.wildwebdeveloper.xml:
{"jsonrpc":"2.0","id":"31","method":"textDocument/completion","params":{"textDocument":{"uri":"file:///home/jeremy/projects/eclipse/source/tycho/demo/osgi-repository/repository/pom.xml"},"position":{"line":36,"character":5}}}
```
For reference issue see: https://github.com/eclipse/lemminx-maven/issues/444

I believe LSP4E has problems in sending a request to the server, - a problem which I'd like to be investigated - so the response cannot be generated, but even if a LS is causing the problem, completion request is never finishes on LSP4E due to "infinite waiting on the completion future by calling `.get()`:
https://github.com/eclipse/lsp4e/blob/55ce45f20dba1147cfa8383412f0105bfe96fc2e/org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/completion/LSContentAssistProcessor.java#L114C11-L114C11
```java
this.completionLanguageServersFuture = LanguageServers.forDocument(document)
	.withFilter(capabilities -> capabilities.getCompletionProvider() != null)
	.collectAll((w, ls) -> ls.getTextDocumentService().completion(param)
		.thenAccept(completion -> proposals.addAll(toProposals(document, offset, completion, w))));
this.completionLanguageServersFuture.get();
```
While it's very difficult to catch the reason of sending request/receiving response failures, the using `CompletableFuture.get()` is to be strongly avoided.

**Comment by angelozerr** [comment]
Using `this.completionLanguageServersFuture.get();` means that you trust the language server, but if language server return a result whish never finish, the this.completionLanguageServersFuture.get() is never free.

If user open several completions, a Thread is taken again from the pool again and after several completion, there is no Thread in the pool and language server becomes unusable not only with completion but with other features like highlighting, validation etc

I suspect that this issue with strange error comes from that there is not Thread in the pool https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/issues/1251

On my side when I edit a pom.xml file after some operations like completion, validation, I loose my all LSP features and I have strange error like https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/issues/1251 and when I try to higlight a tag name, it doesn't work, so I suspect that there is no Thread in the ppol available to process LSP operations.
