### ISSUE TITLE
Enable string interpolation for Json launch parameters

### ISSUE THREAD

**Issue by Si-So** [eclipse/lsp4e#756]
# Steps to reproduce # 
1. Open the Debug Configuration Wizard
2. Create a new configuration for the "Debug Adapter Launcher"
3. Enter valid json in the "Launch parameters" textbox. For example: 
```
{
    "webRoot":"${workspace_loc:/some_project}",
}
```
The plugin does not perform string interpolation for the json launch parameters. In contrast to VS Code, which does (see here: https://github.com/microsoft/vscode-chrome-debug#launch and here: https://github.com/firefox-devtools/vscode-firefox-debug#launch) 

Without string interpolation, it makes no sense to commit the launch configuration to git, because the configurations depend on the directory structure of the commiter. By enabling string interpolation, committing the launch configurations into git makes sense.

**Comment by Si-So** [comment]
The relevant class seems to be `DSPLaunchDelegate.java`

**Comment by mickaelistria** [comment]
@Si-So this is a very valid request. Would you be willing to submit a PR that enables it?

**Comment by Si-So** [comment]
@mickaelistria Yes, I am willing, but I don't know when I will find the time. Maybe next Tuesday.
