### ISSUE TITLE
[debug]When editor already opened but not with the default association, the currently opened editor is not used and a new one is created

### ISSUE THREAD

**Issue by apupier** [eclipse/lsp4e#79]
![anotherEditorOpenedOnBreakpointHit](https://user-images.githubusercontent.com/1105127/154081379-a15d2085-3b60-4849-94a9-c6bfa5aa06a4.gif)

workaround: Window -> Preferences -> General -> File associations and set the default editor

**Comment by sebthom** [comment]
I cannot reproduce the issue in the current LSP4e relese. Please reopen if the issue is still present.
