### ISSUE TITLE
TriggerKind is always TriggerCharacter if char is on completionTriggerChars list

### ISSUE THREAD

**Issue by zulus** [eclipse/lsp4e#794]
During work eclipse-wildwebdeveloper/wildwebdeveloper#1316 I realized that LSP4E ignore way how code assist is invoked, and always mark completion computation as TriggerCharacter if character under cursor is inside completionTriggerChars

Also triggerCharacter is always pushed to server, which is also wrong. For TriggerKind.Invoked should be undefined

Bug has been introduced via https://github.com/eclipse/lsp4e/commit/7c770c390b3148a57818aa19c5b2060825369531

**Comment by mickaelistria** [comment]
@ghentschke Can you please have a look?

**Comment by zulus** [comment]
First problem is complicated because by design IContentAssistProcessor haven't access to ContentAssistEvent, so don't know if it's "auto" or "on-demand".  PDT have ugly workaround via separate ContentAssistant implementation.

To fix second problem, should be enough to drop LSPEclipseUtils.toCompletionParams#237 line.

**Comment by ghentschke** [comment]
I'll check that and provide a PR.

**Comment by ghentschke** [comment]
> To fix second problem, should be enough to drop LSPEclipseUtils.toCompletionParams#237 line

I am not sure if a line drop is right in this situation. I think an empty String as `positionCharacter` would be better. What does undefined mean in the  TriggerKind.Invoked context?

> by design IContentAssistProcessor haven't access to ContentAssistEvent, so don't know if it's "auto" or "on-demand"

@zulus  What is your expected behavior here? Does `on-demand` means `CompletionTriggerKind.TriggerCharacter`? What is the link between the `CompletionTriggerKind` and `ContentAssistEvent`?

**Comment by rubenporras** [comment]
@zulus , @ghentschke , any chance you could have time to improve the eclipse platform so that LSP4E can reliably know if the content assist has been manually invoked or automatically triggered?

**Comment by ghentschke** [comment]
> Also triggerCharacter is always pushed to server, which is also wrong. For TriggerKind.Invoked should be undefined

Fixed by #798

**Comment by ghentschke** [comment]
> and always mark completion computation as TriggerCharacter if character under cursor is inside completionTriggerChars

@zulus can you please open a new issue for this topic.

**Comment by zulus** [comment]
> @zulus can you please open a new issue for this topic.

Done, see #799

> @zulus What is your expected behavior here? Does `on-demand` means `CompletionTriggerKind.TriggerCharacter`? What is the link between the `CompletionTriggerKind` and `ContentAssistEvent`?

I've added extra info to #799

> I'll check that and provide a PR.

Thx for second problem PR, VUE component inside WWD have now much better auto-completion
