### ISSUE TITLE
[debug]When editor already opened but in a project hierarchy, the currently opened editor is not used and a new one is created

### ISSUE THREAD

**Issue by apupier** [eclipse/lsp4e#80]
![anotherEditorOpenedInCaseOfHierarchyFolders](https://user-images.githubusercontent.com/1105127/154082191-683e551c-00e8-4c18-b053-f7c814aabcaa.gif)

**Comment by sebthom** [comment]
I cannot reproduce the issue in the current LSP4e relese. Please reopen if the issue is still present.
