### ISSUE TITLE
Multiple languageservers for same content-type

### ISSUE THREAD

**Issue by zulus** [eclipse/lsp4e#830]
LSP4E currently have undocumented limitation to support only one Languge Server for concrete content-type. Is this intentional?

Vue Language Server in VS studio starts twice, with two different modes to support different capabilities, and due this limitation I cannot do same in WildWebDeveloper

**Comment by mickaelistria** [comment]
> LSP4E currently have undocumented limitation to support only one Languge Server for concrete content-type.

This statement seems wrong in general. There are multiple tests (such as CompletionTests.testMultipleLS) that demonstrates that multiple LS for the same content-type do work. Maybe you found a bogus corner case where it does not work, but it's not an intentional limitation.

**Comment by angelozerr** [comment]
I can confirm that LSP4E supports this issue because in https://github.com/jbosstools/jbosstools-quarkus/ we bind Java content type to 2 language servers (MicroProfile and Qute language servers) and it works perfectly

**Comment by zulus** [comment]
My bad sorry, something goes wrong at first time
