### ISSUE TITLE
Provide the capability to customize manage language mapping

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lsp4e#831]
Today a language server is started if it matches some content type (ex : html content type will start angular LS, vscode HTMl LS, vue LS).

It can be very annoying:

 * for feature, because you could have some validation coming from angular,vue LS when you open an HTML file although the project is not an angular / vue project
 * for performance, too many language server are started and process validation,completion etc when you open html file

It should be nice to provide a new extension point like DocumentMatcher:

```java
public interface DocumentMatcher {

    boolean match(IDocument document, IProject project)
}
```

that you could use it when you define a language mapping

```xml
     <contentTypeMapping contentType="org.eclipse.wildwebdeveloper.ts" 
                                           id="org.eclipse.wildwebdeveloper.angular"
                                           documentMatcher="org.eclipse.wildwebdeveloper.angular.AngularDocumentMatcher"/>


```

```xml
<extension point="org.eclipse.lsp4e.languageServer">
     <server
           class="org.eclipse.wildwebdeveloper.angular.AngularLanguageServer"
           clientImpl="org.eclipse.wildwebdeveloper.angular.AngularClientImpl"
           id="org.eclipse.wildwebdeveloper.angular"
           label="Angular Language Server"/>
     <contentTypeMapping contentType="org.eclipse.wildwebdeveloper.ts" 
                                           id="org.eclipse.wildwebdeveloper.angular"
                                           documentMatcher="org.eclipse.wildwebdeveloper.angular.AngularDocumentMatcher"/>
     <contentTypeMapping contentType="org.eclipse.wildwebdeveloper.html" 
                                           id="org.eclipse.wildwebdeveloper.angular"
                                           documentMatcher="org.eclipse.wildwebdeveloper.angular.AngularDocumentMatcher"/>
   </extension>
```

The `AngularDocumentMatcher`  could match that the project defines an angular.json for instance (or other condition)

```java
public  AngularDocumentMatcher implements DocumentMatcher {

    @Override
    public match(IDocument document, IProject project) {
          return project.getFile("angular.json").exists();
    }

}
```

This document matcher will be very helpfull too for MicroProfile / Qute language server where java file is matched to those language server. For non Qute / MicroProfile project, when java file is opened, the language servers should never started and java file should never connected to those language servers.

//cc @sbouchet @zulus @vrubezhny

**Comment by zulus** [comment]
This is why, I for now I didn't register extra content mapping for vue ls, in theory could be activated if user enable some config (for example petitieVue support for html)

Should be strong information, that this matcher might be executed only once if LS support WorkspaceFolders. And this looks similar to way how vscode extensions starts his servers, they prepare list of DocumentFilter objects, your proposition is more powerful, if you need IDocument for verification I'm afraid potential deadlock due ConnectDocumentToLanguageServerSetupParticipant

Anyway, in theory this could (and probably should) be implemented via enableWhen by own tester, but for now EnablementTester always create document so it's too late (temporaryLoadDocument) due ConnectDocumentToLanguageServerSetupParticipant again :P

**Comment by mickaelistria** [comment]
If you need IDocument, then you should instead use an IContentDescriber on the ContentType definition. That allows to only turn on a content-type according to some particular document content. See for example how ShellWax uses it to identify any file as being bash if it has a shebang.
So IMO, the case of document content is already well and better handled with content-type support.

The case of another environment info to decide whether to turn on a LS or not doesn't yet have a proper solution in LSP4E. I'm aware some customers just put some listeners here and there and explicitly turn on a particular LS for a particular file under a particular condition. I believe it kind of makes sense, as just defining the criterion (which is what is proposed here) may not be enough: someone changing the environment after the file is opened (ie I add a angular.json file after the .ts file is open, or I change a preference, or....) would still require a custom listener anyway.

**Comment by angelozerr** [comment]
> if you need IDocument for verification I'm afraid potential deadlock due ConnectDocumentToLanguageServerSetupParticipant

I have not some usecase about using IDocument, the only usecase is to have the URI name (to check for instance that the uri belongs to a folder, or matches a given name). The mapping check is done:

 * https://github.com/eclipse/lsp4e/blob/cb8f91739c908b6ddd00388ccc84f7a210d1540e/org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServiceAccessor.java#L304 and the method have an IDocument
 * and https://github.com/eclipse/lsp4e/blob/cb8f91739c908b6ddd00388ccc84f7a210d1540e/org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServiceAccessor.java#L245 which is working with IFile

We could have different signature like:

```java
public interface DocumentMatcher {

    boolean match(IDocument document, URI fileUri, IProject project)

    boolean match(IFile file, URI fileUri, IProject project)
}

```

**Comment by zulus** [comment]
See org.eclipse.lsp4e.enablement.EnablementTester. It resolve URI -> resource -> document as variables

**Comment by angelozerr** [comment]
> ie I add a angular.json file after the .ts file is open, or I change a preference, or....

Indeed I have not spoken about this feature (because I wanted at first explain the main idea), but we need that too, but LSP4E should provide this mechanim like, I mean that LSP4E should provide an API to re-evaludate the disconnect / connect of files which are opened in the workspace.

**Comment by angelozerr** [comment]
Please note that I'm implementing this Docmentmatcher idea in LSP4IJ https://github.com/redhat-developer/intellij-quarkus/pull/1188/files and it starts working : 

 * when you open a Java file, it starts the proper language servers (and not Qute / MicroProfile language servers both)

**Comment by angelozerr** [comment]
> As mentioned by @zulus , using the enabledWhen tag under the contentTypeMapping already allows to prevent a LS from being start based on the document or its URI. So this does cover what's needed here as one can contribute complex conditions, developed in Java, to enabledWhen already.

Nice!

> As for the listeners, if the things to listen to are LS-specific and can be anything, then it cannot be what the responsibility of LSP4E to provide a framework to listener to anything. Eclipse Platform already does it, and users can just call the necessary code to refresh LS attached to some Files when needed.

We need to implement a concrete usecase to see if it could be interesting that LSP4E provide an API to re-evaludate connect/disconnect of opened files which matches a given enableWhen

> I don't know if IJ provides similar things. Maybe you do need an extra class for that in IJ, but in Eclipse, I don't think there is the need for it.

Indeed in IJ I need that, that's cool that Eclipse provide this feature out of the box.

**Comment by mickaelistria** [comment]
>  We need to implement a concrete usecase to see if it could be interesting that LSP4E provide an API to re-evaludate connect/disconnect of opened files which matches a given enableWhen

IIRC, Spring Boot integration already does that: there is enabledWhen which makes that the LS is only enabled under some condition, and they have some listeners in place to retrigger LS check from time to time.
Note that the way language servers are looked up makes that if 1 language server becomes enabled suddenly (enabledWhen becomes true), then the next request to get language servers for this document would start the newly enabled LS.
