### ISSUE TITLE
Restart LS via LanguageServerWrapper

### ISSUE THREAD

**Issue by ddscharfe** [eclipse/lsp4e#839]
In cdt-lsp we want to restart the language server when a configuration file changes (https://github.com/eclipse-cdt/cdt-lsp/issues/214). 

This was already discussed in #726. 
Calling `LanguageServerWrapper::start` and then `LanguageServerWrapper::stop` is not sufficient, because this will not refresh the open editors instantly. 
What we'd like to have is a method `LanguageServerWrapper::restart()`, which stops and starts the language server and reconnects the documents. `LanguageServerWrapper::start()` already supports this, but only restarts if the server is inactive. 

I will provide a PR if there are no objections to this feature.

**Comment by sebthom** [comment]
This is implemented since [0.24.3](https://github.com/eclipse/lsp4e/releases/tag/0.24.3)
