### ISSUE TITLE
missing pom.xml files for submodules?

### ISSUE THREAD

**Issue by clandestinenetworks** [eclipse/lsp4e#86]
Hey I had a question about the build for lsp4e I found that the modules are specified in the root projects pom.xml 

```
<module>org.eclipse.lsp4e.jdt</module>		<module>org.eclipse.lsp4e.debug</module>
<module>org.eclipse.lsp4e.tests.mock</module>
```

If I try to build this with maven it says the modules are not found; it is able to find modules though but the ones that it can find have a pom.xml in the project subdir. I was just wondering why that's not consistent

**Comment by jonahgraham** [comment]
Hi @clandestinenetworks - sorry to hear you ran into a problem.
Can you share the command line you use and the error you got?

**Comment by clandestinenetworks** [comment]
yeah I'm kinda starting to realize that about it, seems like in order to build this you need to do it from the command line with `mvn` because idea doesn't get tycho. 

Thank you, an if you would be so inclined to tell me what you know about (ie: remote debugging eclipse with eclipse/idea) feel free otherwise feel otherwise you can close the ticket as Tycho was definitive answer I was looking for and I'll post on corrosion issues later. I'm guessing nobody does that at all, but just in case there is somebody with some context I'd like to get it setup.

**Comment by jonahgraham** [comment]
Thanks for your questions, but sorry I don't know what more I can offer you in this area. Eclipse supports [remote Java debugging](https://help.eclipse.org/latest/topic/org.eclipse.jdt.doc.user/concepts/cremdbug.htm?cp=1_3_6_2) - but not sure if that is what you want here.

**Comment by mickaelistria** [comment]
@clandestinenetworks If you want to work on development of Eclipse plugins, you'll need to use Eclipse SDK or IDE (different but similar packages) with Eclipse Plugin Development Environment installed. From here, the IDE can build projects and allow to spawn unit tests or children IDE to test your changes in a few clicks.
