### ISSUE TITLE
Latest version not submitted to simrel

### ISSUE THREAD

**Issue by akurtakov** [eclipse/lsp4e#875]
A commit like https://github.com/eclipse-simrel/simrel.build/commit/7dc8fd4f3c7db229f1ade1bfc926fc4e5e78830d is all that should be needed.

**Comment by akurtakov** [comment]
It would be nice to submit to simrel when a release is done, even have it as a step in the release process. 
@rubenporras Do you think you can find time for this one as you did the last release?

**Comment by rubenporras** [comment]
Yes, I can do that. @mickaelistria , I suggest we do another minor release with the latest fixes of the last 3 weeks and add that to the simrel. Do you agree?

**Comment by mickaelistria** [comment]
@rubenporras +1 for a release as I'm not aware of major ongoing changes or immature new APIs since last release that would prevent from a safe release.

**Comment by rubenporras** [comment]
https://github.com/eclipse-simrel/simrel.build/pull/63

**Comment by akurtakov** [comment]
@rubenporras can you push yourself? If not I'll push it this time and nominate you for simrel committer.

**Comment by rubenporras** [comment]
Hi @akurtakov , I cannot push myself, I am happy if you can do it and if you want to nominate me for the next time.
Regards

**Comment by akurtakov** [comment]
Just nominated you https://projects.eclipse.org/projects/technology.simrel/elections/election-rub%C3%A9n-porras-campo-committer-eclipse-simrel
