### ISSUE TITLE
Performance problems with code minings in the presence of partitioning

### ISSUE THREAD

**Issue by ahmedneilhussain** [eclipse/lsp4e#882]
Hi all,

Our LS plugin uses LSP4e but (perhaps unusually) we don't use TM4e. We have a few custom extension classes of our own to implement syntax highlighting, which I think we originally based on the java editor.

We extend a standard implementation of [IDocumentPartitioner](https://help.eclipse.org/latest/topic/org.eclipse.platform.doc.isv/reference/api/org/eclipse/jface/text/IDocumentPartitioner.html) to provide our own partitioning. As I understand it, this is an optimisation to speed up syntax colouring and other analysis: the partitioning splits the source up into very high-level typed chunks so that e.g. string literals and comments are separate partitions to other chunks of code. The rationale seems to be that one doesn't need to perform detailed tokenisation within string literals or comments, one just needs to find the end of the literal/comment.

So far, so good. However we've just run into some performance problems with some larger but not huge source files (~2k lines). When I tracked it down I discovered every time I typed a character LSP4e fired off loads of requests for code lenses and inlay hints. I found by putting a `System.err.println` in `CodeLensProvider.provideCodeMinings()` that some source files triggered the call many times for each character I typed, some triggered it a couple of times, and some triggered it once. It turned out that this could be explained by the number of string literals/comments: the files that had only 1 'code' partition with no comments or string literals only triggered a single request.

The problem seems to be the way the code mining reconciler interacts with partitioning.
From https://github.com/ahmedneilhussain/eclipse.platform.ui/blob/dfad87dad2613cd18bb760b53d9cbbb36af9cd49/bundles/org.eclipse.jface.text/src/org/eclipse/jface/text/reconciler/Reconciler.java#L143
and the following stack trace
```
  
  CodeLensProvider.provideCodeMinings(ITextViewer, IProgressMonitor) line: 66	
CodeMiningManager.lambda$2(ITextViewer, IProgressMonitor, ICodeMiningProvider) line: 189	
0x000000080138f758.apply(Object) line: not available	
ReferencePipeline$3$1.accept(P_OUT) line: 197	
Spliterators$ArraySpliterator<T>.forEachRemaining(Consumer<? super T>) line: 992	
ReferencePipeline$3(AbstractPipeline<E_IN,E_OUT,S>).copyInto(Sink<P_IN>, Spliterator<P_IN>) line: 509	
ReferencePipeline$3(AbstractPipeline<E_IN,E_OUT,S>).wrapAndCopyInto(S, Spliterator<P_IN>) line: 499	
ReduceOps$3(ReduceOps$ReduceOp<T,R,S>).evaluateSequential(PipelineHelper<T>, Spliterator<P_IN>) line: 921	
ReferencePipeline$3(AbstractPipeline<E_IN,E_OUT,S>).evaluate(TerminalOp<E_OUT,R>) line: 234	
ReferencePipeline$3(ReferencePipeline<P_IN,P_OUT>).collect(Collector<? super P_OUT,A,R>) line: 682	
CodeMiningManager.getCodeMinings(ITextViewer, List<ICodeMiningProvider>, IProgressMonitor) line: 195	
CodeMiningManager.updateCodeMinings() line: 140	
CodeMiningManager.run() line: 129	
ExtensionBasedTextEditor$1(SourceViewer).updateCodeMinings() line: 1333	
CodeMiningStrategy.reconcile(IRegion) line: 56	
CodeMiningReconciler(Reconciler).process(DirtyRegion) line: 151	
AbstractReconciler$BackgroundThread.run() line: 207	
```
it turns out that `provideCodeMinings` gets called once per edit, per 'normal' partition. This is obviously inefficient since `provideCodeMinings` operates at the whole document level, so the same information is being requested many times. Moreover, there's nothing in the LSP protocol about getting code lenses for a portion of the document rather than the whole even if we wanted to try and scope the requests. That's not the case for inlay hints, but at the moment we don't support it, and in any case `ICodeMiningProvider` doesn't have a way of scoping requests anyway.

Does anyone have any thoughts on this? I notice that tm4e doesn't seem to implement anything w.r.t. partitioning. Should I consider partitioning to be an obsolete optimisation that is no longer really used/necessary? TM4e can happily syntax colour a Rust file of ~2k lines without any trouble, which it appears to be able to do in a single flat pass without any need for a crude first pass.

 Any observations/suggestions welcome! At the moment I don't think lsp4e has anything by way of throttling of requests, but ISTR some discussions along these lines..?

Thanks

**Comment by angelozerr** [comment]
Code mining follows the same behavior than vscode codelens. There is a first step which create codeming on a given position with some content if it is fast to compute it or a empty content if the content of a codemìng is slow to compute and it is done in a separate completeabke future in reslove method.

Codeming is not linked to the eclipse partition to be generic. For instance lsp works without eclipse partition since the parse of tokens is delegate to the langu1ge server.

TM4E works exactly th1n vscode since I had started this project by copying pastzd vscode textmate written in TypeScript that I had translated to Java.

The basic idea of textamte parsing is that it needs the state of the previous line if I remember to compute the next token. 

As the textmate parser is generic , it is used in netbeans for instance  I think but not sure with that  the parszr is not linked to the partitionning mechanism of eclipse and textmate have not this mechanism.

I m surprised that you have pzeformance with codemining if your ls doednt support codelens or inlayhint.

Is your ls returns the codeLensProvider or inlayHintProvider capability?

**Comment by ahmedneilhussain** [comment]
Hi @angelozerr thanks for the answer and sorry for not following up sooner, I was on holiday.

Our LS does indeed support code lenses and inlay hints, although we don't currently support the separate resolve phase and return the minings fully resolved in the immediate response: since the work needed by our LS to compute the possible minings produces the resolutions 'for free' there is no benefit in having a separate resolve step, other than possibly reducing up-front network traffic.

I can totally get that TM4e doesn't have anything to do with partitioning, since it's a very eclipse concept that doesn't map to anything in VSCode. It acts as a crude optimisation since by caching the partitions damage repairers (e.g. for syntax highlighting) only need to retokenise a subset of the document. TM4e goes better than this by just caching all the tokens if I understand correctly.

It looks to me like the code mining API was added to eclipse (and certainly to LSP4e) without much thought given for partitioning, since the code minings get refreshed per partition but in the upper layers of API there is nothing to scope the requests to individual parts of a document.

I've tried rewriting our coloriser to just scan the whole document without using partitions, and it seems to be just about fast enough. Unfortunately it looks liked we'd have to build any optimisation ourselves, e.g. caching tokens as TM4e does.

**Comment by angelozerr** [comment]
@ahmedneilhussain if I understand your comment, by rewriting your scanner for syntax coloration you have food performance. Is it that?

If it that it me1ns that it is not a codelens problem. Lsp4e supporrs lsp codelens by using codemining api which follows the same beh1vior than vscode.

Codeming is used in jdt and it seems performance are good.

Codemining are managed  with completablefuture so it should never freeze the eclipse ide.

As you use a language server I suppose that your goal is to integrate it in another lsp clients like vscode.

IMHO you should manage syntax color1tion ,ith tewmate or lsp semantic tokens

**Comment by ahmedneilhussain** [comment]
> @ahmedneilhussain if I understand your comment, by rewriting your scanner for syntax coloration you have food performance. Is it that?
Much better performance overall, yes. The actual syntax highlighting was running slower because it was doing a lot more work (re-parsing the whole document rather than just the damaged partition). However it did stop the code minings from causing big performances problems with a large document.
 
> If it that it me1ns that it is not a codelens problem. Lsp4e supporrs lsp codelens by using codemining api which follows the same beh1vior than vscode.
Not necessarily true. The problem wasn't that our syntax highlighting was slow, the problem was that our syntax highlighting used partitioning, and having multiple partitions plays really badly with the code mining logic. If you look at the stack trace above and how `Reconciler.process(DirtyRegion)` works and how the code mining reconciliation works, it's not too hard to see how codeminings will be redundantly requested for the whole document multiple times for each code edit (once per partition).

> Codeming is used in jdt and it seems performance are good.
They'll be fine so long as there is only one partition!

> Codemining are managed with completablefuture so it should never freeze the eclipse ide.
It doesn't lock up the UI but with large documents with lots of code minings and multiple partitions it really hammers the server and adds a lot of load on the client machine. It creates so much load on the server in particular that hover requests and completions just start timing out.

> As you use a language server I suppose that your goal is to integrate it in another lsp clients like vscode.
Very like vscode indeed! I've been busy with that for much of the last year, which is why I've not been in Eclipse/lspe land so much.

> IMHO you should manage syntax color1tion ,ith tewmate or lsp semantic tokens
We use text mate for our 'project config' files but have our own partition-based highlighter for our main source files. When we initially wrote our plugin we tried tm4e for both but found that it wasn't quite mature enough at the time and had synchronisation issues. I think there's been quite a lot of progress in that area so we will reevaluate it when we get a chance: we're generally keen to use o/s components rather than maintaining our own ;-)

**Comment by angelozerr** [comment]
> They'll be fine so long as there is only one partition!

Uunderstood! It is a problem with codemining, I suggest that you create an issue to https://github.com/eclipse-platform/eclipse.platform.ui/issues  

>  I think there's been quite a lot of progress in that area so we will reevaluate it when we get a chance: we're generally keen to use o/s components rather than maintaining our own ;-)

I suggest that you retry it, because @sebthom has worked hard to improve tm4e

**Comment by sebthom** [comment]
Closing the issue for now. If the problem persists or reappears feel free to reopen.
