### ISSUE TITLE
Eclipse IDE reports CTRL+SHIFT+T keybing conflict on start-up

### ISSUE THREAD

**Issue by trancexpress** [eclipse/lsp4e#883]
To reproduce, download the Eclipse installer and install the latest (e.g. 2023-12) Eclipse IDE for Java developers: https://www.eclipse.org/downloads/packages/installer

Start the installed Eclipse in a new workspace, observe logged warning:

```
eclipse.buildId=4.30.0.20231201-1200
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.java.product

org.eclipse.jface
Warning
Fri Dec 15 10:52:04 CET 2023
A conflict occurred for CTRL+SHIFT+T:
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,Open Type,
		Open a type in a Java editor,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		WorkbenchHandlerServiceHandler("org.eclipse.jdt.ui.navigate.open.type"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.lsp4e.symbolinworkspace,Go to Symbol in Workspace,
		,
		Category(org.eclipse.lsp4e.category,Language Servers,null,true),
		WorkbenchHandlerServiceHandler("org.eclipse.lsp4e.symbolinworkspace"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
```

Same issue as: https://github.com/eclipse/lsp4e/issues/38
It was closed via fixing https://github.com/eclipse-platform/eclipse.platform.ui/issues/513 and https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/476, but the logged conflict remains.

**Comment by trancexpress** [comment]
No new arguments to add, aside from the ones already mentioned in the issues (and in linked issues thereof):

- https://github.com/eclipse/lsp4e/issues/38
- https://github.com/eclipse-platform/eclipse.platform.ui/issues/513
- https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/476

**Comment by mickaelistria** [comment]
As enabledWhen allow a very fine activation policy that cannot be checked statically at startup, I think Platform should simply not log such "conflicts" in case it they are known to be actually conflicting (ie the actual shortcut is pressed, both bindings can resolve to an active handler).

**Comment by trancexpress** [comment]
> As enabledWhen allow a very fine activation policy that cannot be checked statically at startup, I think Platform should simply not log such "conflicts" in case it they are known to be actually conflicting (ie the actual shortcut is pressed, both bindings can resolve to an active handler).

Assuming its possible to check for the presence of `enabledWhen`, how about we log an info (instead of a warning) from the platform code? If there is no `enabledWhen` we continue to log a warning.

Or we just log an info instead of a warning.

Yet to get an answer from my team to know if this is sufficient for us.

**Comment by mickaelistria** [comment]
> Assuming its possible to check for the presence of enabledWhen, how about we log an info (instead of a warning) from the platform code? If there is no enabledWhen we continue to log a warning.

I think it would be a good improvement.

**Comment by trancexpress** [comment]
Set a PR for platform UI: https://github.com/eclipse-platform/eclipse.platform.ui/pull/1508

If we merge the change, I think we can close the issue here.

**Comment by mickaelistria** [comment]
Perfect, thanks!
