### ISSUE TITLE
Editor text got broken when inserting a multiline CA proposal in some cases  

### ISSUE THREAD

**Issue by vrubezhny** [eclipse/lsp4e#89]
The original issue: https://github.com/eclipse/lemminx-maven/issues/276

The actual issue is that `LSCompletionProposal.apply()` method doesn't updates the proposal's additional `TextEdit`-s Ranges according to the number of characters typed by a user between the moment of CA is invoked and the moment of proposal is applied on the document. As result, the document gets corrupted. 

Steps to reproduce:
- Consider editing Maven Project like the following:

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <artifactId>foo-child</artifactId>
  <packaging>pom</packaging>
  <name>FOO Child</name>
  <dependencies>
	<dependency>
		<artifactId>org.ecl|</artifactId>
	</dependency>
  </dependencies>
</project>
``` 
- Place the cursor in text instead of "|" character and press Ctrl-Space to invoke the content assistant
- Continue typing characters, for example `ipse.lem` in order to make `org.eclipse.lemminx`  artifact to be the first selected proposal, then insert the selected proposal
- See the proposal inserted breaking the existing code:
```
	<dependency>
		<groupId>org.eclipse.lemminx</groupId>
		<artifactId>org.eclipse.lemminx</art
		<version>0.19.1</version>ifactId>
	</dependency>
```

**Comment by mickaelistria** [comment]
@vrubezhny Is #90 expected to be sufficient here to resolve this issue?

**Comment by vrubezhny** [comment]
> @vrubezhny Is #90 expected to be sufficient here to resolve this issue?

Yes it is sufficient
