### ISSUE TITLE
adjustments to additionalTextEdits  are slightly off when on different line (when applying a proposal)

### ISSUE THREAD

**Issue by martinlippert** [eclipse/lsp4e#896]
I have content-assist proposals with additionalTextEdits that affected pieces of the document behind the current cursor position. But it looks like the position of the additionalTextEdits, when applied, is not adjusted with regards to a potential changed document.

Here is the exact case:
- I type a character, the client asks the language server for completion proposals
- the completion proposals contain additionalTextEdits that are calculated based on the document state when the completion proposals where requested
- now the user continues typing and the client filters the list of proposals (based on the changed prefix), the client does not ask the server for new completion proposals
- now the client applies the completion proposal. The additionalTextEdits need to be adjusted with regards to the additional characters the user typed since the client asked the server for the completion proposals.

Please note that the extra call to the server to resolve completion proposals doesn't help here, because this resolve call gets called when the user scrolls to the completion proposal in the UI (the proposals popup), it does not happen after the user typed additional characters.

**Comment by martinlippert** [comment]
Another note:
This is, of course, only necessary if the additionalTextEdits have a start offset that is greater than the cursor position (at the time of requesting the completion proposals).

AdditionalTextEdits that appear before the current cursor position (e.g. automated insertion of new import statements) work nicely, of course.

**Comment by mickaelistria** [comment]
Fixes with #897
