### ISSUE TITLE
Impossible to select an element in the C++ LSP Quick Outline view with a keyboard

### ISSUE THREAD

**Issue by travkin79** [eclipse/lsp4e#900]
I observed a very strange behavior when using the C++ LSP quick outline view. Selecting an element with the up and down keys doesn't work. Hitting one of the keys closes the view. It would ne nice if this view would behave similar to JDT's quick outline view for Java code.

**Details**
As soon as the selection in the quick outline view changes, e.g. when using the up and down keys in order to select the element to navigate to, the view is closed immediately. Users have no chance to select the desired element with the up and down keys.
(Clicking on an element with the mouse seems to work as expected.)

This issue is related to PR #888.

**Comment by rubenporras** [comment]
Hi @travkin79 ,

would you like to create a PR for the fix of your latest PR?

Regards

**Comment by travkin79** [comment]
Hi @rubenporras,
I've created PR #901, but there seem to be some time-out problems in the tests. A few tests are failing. I'm not sure how they relate with my changes. Any idea what I am doing wrong?
Best regards.
Dietrich

**Comment by rubenporras** [comment]
Thanks for the PR. Yes, some of the tests are flaky, if you have looked at them, think they are unrelated, and do not fail consistently on your PR, I would not worry much about them.
