### ISSUE TITLE
deadlock i think in lsp4e code for markers, (deadlock in the workspace lock)

### ISSUE THREAD

**Issue by jcompagner** [eclipse/lsp4e#920]
[stackdump](https://github.com/eclipse/lsp4e/files/14278148/txt.txt)

see the at attached file, my eclipse never gets out of it and i need to kill it

**Comment by mickaelistria** [comment]
Is this happening with latest snapshots of LSP4E?

**Comment by jcompagner** [comment]
i have updated now everything to the latest snapshots, lets see if i can reproduce this again

**Comment by sebthom** [comment]
I am closing this ticket for now. If the error occurs again please reopen and provide a new stackdump.
