### ISSUE TITLE
SimRel Participation?

### ISSUE THREAD

**Issue by merks** [eclipse/lsp4e#936]
Is the project still actively participating in SimRel?

I see a bunch of new releases here:

- https://download.eclipse.org/lsp4e/releases/

Yet I see no corresponding release records beyond 0.24.5, which is the version currently contributed to SimRel:

- https://github.com/eclipse-simrel/simrel.build/blob/b42809044c9ffef4cb57c7047c01c7b0c03bd556/lsp4e.aggrcon#L3

Worst yet, the most recent release is still requiring specifically an older version of lsp4j:

![image](https://github.com/eclipse/lsp4e/assets/208716/f3bad240-b5a5-406b-b4e5-1fdd123ab3a0)

@akurtakov @jonahgraham  Do you guys know what's going on here?  I would just remove this from SimRel, but there is an awful lot downstream from this:

![image](https://github.com/eclipse/lsp4e/assets/208716/20354880-3b15-49dd-aa30-2260edf143dd)

Either the project itself needs to step up or someone downstream needs to step up and contribute in order to keep this project on track for SimRel.

**Comment by jonahgraham** [comment]
The update to latest LSP4J was made in https://github.com/eclipse/lsp4e/pull/919 - but there was a push to do a last release with the older LSP4J. In the #919 there was this comment that indicated a new release was needed https://github.com/eclipse/lsp4e/pull/919#issuecomment-1943427692 but that doesn't seem to have happened yet.

@akurtakov it looks like you have been doing a bunch of releng stuff on WWD - not sure if a new release is imminent there or possible in the timescale. I can do an LSP4E release tomorrow/Friday which has #919 included. 

---

As far as contribution update + release records - @rubenporras did the recent builds and did the contribution on previously built versions. My guess is some items are missing from LSP4E's release checklist - although for release records that will hopefully be a thing of the past once https://gitlab.eclipse.org/eclipsefdn/it/websites/projects.eclipse.org/-/issues/146 is resolved, but until then LSP4E should have them.

The scheduling of LSP4J was supposed to be early enough in the release cycle to allow downstream projects to upgrade. xtext has made the updated release.

I see something strange in the required IUs tab:

![image](https://github.com/eclipse/lsp4e/assets/679236/d4513228-35d6-461e-9b67-06ce8d6785b2)

**Comment by merks** [comment]
I don't personally actually care about release records and it will be nice to have one less thing that needs to be managed.

As for the duplicates in the Required IUs view, if you look at the detailed links between the requirements and the capabilities, you'll see that both versions of lsp4j satisfy the requirement so either of them is a potential required IU:

![image](https://github.com/eclipse/lsp4e/assets/208716/724e7741-4d1c-402d-8e2c-20fae824775f)

So they are duplicates in the view simply because duplicates exist and each duplicate is within the specified version range.

**Comment by akurtakov** [comment]
> The update to latest LSP4J was made in #919 - but there was a push to do a last release with the older LSP4J. In the #919 there was this comment that indicated a new release was needed [#919 (comment)](https://github.com/eclipse/lsp4e/pull/919#issuecomment-1943427692) but that doesn't seem to have happened yet.
> 
> @akurtakov it looks like you have been doing a bunch of releng stuff on WWD - not sure if a new release is imminent there or possible in the timescale. I can do an LSP4E release tomorrow/Friday which has #919 included.
>

WWD release in time for 2024-03 is out of question from my side. Fixing to work with latest TS LS, using latest grammars from TM4E and so on and on is what I would like to see before a release. There is even https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/13284 which happened due to ^ nodejs versioning so we can't even release before this one is approved.

**Comment by merks** [comment]
I don't think anything else needs to change in order for there to be a new version of lsp4e that doesn't lock in an older version of lsp4j, i.e., I only see lower bounds for lsp4e, no upper bounds:

![image](https://github.com/eclipse/lsp4e/assets/208716/1f3a9b02-7236-4ddd-9106-9cc9fbb5aaa6)

**Comment by akurtakov** [comment]
And https://ci.eclipse.org/simrel/ is down

**Comment by rubenporras** [comment]
@akurtakov , shall I do a new release which is built against?

**Comment by akurtakov** [comment]
> @akurtakov , shall I do a new release which is built against?

Build against latest lsp4j? Yes, that would be nice.

**Comment by rubenporras** [comment]
I will do that. I will wait till the end of today if you do not mind to see if we can merge https://github.com/eclipse/lsp4e/pull/933

**Comment by akurtakov** [comment]
> I will do that. I will wait till the end of today if you do not mind to see if we can merge #933

Deadline for changes is next Wednesday. If I see a release this week I'll contribute to simrel but if it's next week please do it yourself as I won't be available.

**Comment by jonahgraham** [comment]
Thanks @rubenporras - feel free to reach out to me if you need anything - especially when @akurtakov is away.

**Comment by jonahgraham** [comment]
> I will do that. I will wait till the end of today if you do not mind to see if we can merge #933

Is there any update on this?  At this point I suspect for 2024-03 we should just stick with the already released 0.24.8 release and have two versions of LSP4J in 2024-03.

**Comment by rubenporras** [comment]
I am planning to do a release this morning

**Comment by rubenporras** [comment]
Simrel updated in https://github.com/eclipse-simrel/simrel.build/pull/269
