### ISSUE TITLE
Linked editing doesn't exit on whitespaces and other non-word chars

### ISSUE THREAD

**Issue by vrubezhny** [eclipse/lsp4e#94]
When editing a "linked" element, like `<h3|></h3>`, for example, typing in any characters at position pointed by "|" in opening tag gets reflected (copied) to the linked closing tag which is a wrong behavior.

**Comment by mickaelistria** [comment]
https://github.com/eclipse/lsp4e/commit/f427e37b222fbc56e481127fc7e950ba383a6462 should improve this a bit. However, it doesn't (yet) add support for `wordPattern`.

**Comment by sebthom** [comment]
Fixed by https://github.com/eclipse/lsp4e/pull/100 and https://github.com/eclipse/lsp4e/pull/95
