### ISSUE TITLE
Add References to editor context menu

### ISSUE THREAD

**Issue by ghentschke** [eclipse/lsp4e#944]
As editor user I want to access the References of a symbol via the context menu in the editor:

![image](https://github.com/eclipse-cdt/cdt-lsp/assets/123444711/9fad72e3-384b-451d-8a05-5cd41ea6d31a)

**Comment by mickaelistria** [comment]
I see a "Find References" entry in the context menu of generic editor with underlying LS available.

**Comment by ghentschke** [comment]
Hm, that could be implemented in another bundle? Haven't found anyhing in LSP4E. And in the CDT C/C++ Editor we have no such entry:
![image](https://github.com/eclipse/lsp4e/assets/123444711/8030757a-7f5f-4aee-8e4a-27175ffb4650)

**Comment by ghentschke** [comment]
I'll close this issue here. It should be implemented in cdt-lsp project, since its part of the `org.eclipse.ui.genericeditor.findReferences` command which must be enabled in the CDT C/C++ editor.
