### ISSUE TITLE
LSPEclipseUtils.FILE_URI should be 'file:' instead of 'file://'

### ISSUE THREAD

**Issue by ylussaud** [eclipse/lsp4e#974]
A file URI starts with `file:` not necessarily with `file://` see the [Wikipedia](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier) page for more details.

**Comment by mickaelistria** [comment]
The type of URI we usually want in LSP4E is the one described in https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#uri .

**Comment by ylussaud** [comment]
OK this issue is not relevant, I'll change URIs on my side.
Thank you.
