### ISSUE TITLE
"[Info]	ESLint server running in node v18.18.2" keeps showing up in logs

### ISSUE THREAD

**Issue by kohlschuetter** [eclipse/lsp4e#992]
I keep seeing multiple entries of the following message in the Error Log

```
[Info]	ESLint server running in node v18.18.2
```

Does this mean that the server gets restarted? Why? I don't see a corresponding error message.
If there was an error, it should be shown.
If there was no error, the message should not appear again in the logs.

(I use the error log to check for new messages coming from a specific Maven plugin, and this repetitive noise is quite annoying)

```
eclipse.buildId=4.32.0.20240502-0721
java.version=21.0.3
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=aarch64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product -keyring /Users/ck/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch aarch64 -product org.eclipse.epp.package.jee.product -keyring /Users/ck/.eclipse_keyring
```

**Comment by sebthom** [comment]
LSP4E does not provide ESLint server. If you have an actual issues with it please open a ticket in the corresponding repo at https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper

**Comment by kohlschuetter** [comment]
following up with https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/issues/1549
